<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 15 Análise de Regressão por Polinômios Ortogonais | Curso do R do GIEU</title>
  <meta name="description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 15 Análise de Regressão por Polinômios Ortogonais | Curso do R do GIEU" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 15 Análise de Regressão por Polinômios Ortogonais | Curso do R do GIEU" />
  
  <meta name="twitter:description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  

<meta name="author" content="José C. Barbosa &amp; Alan R. Panosso" />


<meta name="date" content="2020-10-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="experimentos-em-parcelas-subdivididas.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">curso_GIEU</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUÇÃO AO CURSO</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#alguns-conceitos-básicos"><i class="fa fa-check"></i><b>1.1</b> Alguns conceitos básicos</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#medidas-de-posição-e-de-tendência-central"><i class="fa fa-check"></i><b>1.2</b> Medidas de posição e de tendência central</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html"><i class="fa fa-check"></i><b>2</b> COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES</a><ul>
<li class="chapter" data-level="2.1" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html#comparação-da-variância-de-duas-populações-normais"><i class="fa fa-check"></i><b>2.1</b> Comparação da variância de duas populações normais</a></li>
<li class="chapter" data-level="2.2" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html#comparação-de-duas-médias-de-populações-normais-amostras-independentes"><i class="fa fa-check"></i><b>2.2</b> Comparação de duas médias de populações normais: amostras independentes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html"><i class="fa fa-check"></i><b>3</b> PLANEJAMENTO DE EXPERIMENTOS</a><ul>
<li class="chapter" data-level="3.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>3.1</b> Introdução</a></li>
<li class="chapter" data-level="3.2" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#unidade-experimental-ou-parcela"><i class="fa fa-check"></i><b>3.2</b> Unidade Experimental ou Parcela</a></li>
<li class="chapter" data-level="3.3" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#princípios-básicos-da-experimentação"><i class="fa fa-check"></i><b>3.3</b> Princípios Básicos da Experimentação</a></li>
<li class="chapter" data-level="3.4" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#relação-entre-os-princípios-básico-da-experimentação-e-os-delineamentos-experimentais"><i class="fa fa-check"></i><b>3.4</b> Relação entre os princípios básico da experimentação e os delineamentos experimentais</a></li>
<li class="chapter" data-level="3.5" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#testes-de-significância"><i class="fa fa-check"></i><b>3.5</b> Testes de Significância</a></li>
<li class="chapter" data-level="3.6" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#teste-f-de-snedecor-para-análise-de-variância"><i class="fa fa-check"></i><b>3.6</b> Teste F de Snedecor para Análise de Variância</a></li>
<li class="chapter" data-level="3.7" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#exemplo-de-aplicação-do-teste-f"><i class="fa fa-check"></i><b>3.7</b> Exemplo de aplicação do teste F</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html"><i class="fa fa-check"></i><b>4</b> TESTES PARA COMPARAÇÃO DE MÉDIAS</a><ul>
<li class="chapter" data-level="4.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>4.1</b> Introdução</a></li>
<li class="chapter" data-level="4.2" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#contrastes-de-médias"><i class="fa fa-check"></i><b>4.2</b> Contrastes de Médias</a></li>
<li class="chapter" data-level="4.3" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#estimativa-do-contrastes"><i class="fa fa-check"></i><b>4.3</b> Estimativa do Contrastes</a></li>
<li class="chapter" data-level="4.4" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#covariância-entre-dois-contrastes"><i class="fa fa-check"></i><b>4.4</b> Covariância entre dois contrastes</a></li>
<li class="chapter" data-level="4.5" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>4.5</b> Contrastes ortogonais</a></li>
<li class="chapter" data-level="4.6" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#variância-de-um-contraste"><i class="fa fa-check"></i><b>4.6</b> Variância de um contraste</a></li>
<li class="chapter" data-level="4.7" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#erro-padrão-do-contraste"><i class="fa fa-check"></i><b>4.7</b> Erro padrão do contraste</a></li>
<li class="chapter" data-level="4.8" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-t-de-student"><i class="fa fa-check"></i><b>4.8</b> Teste t de Student</a></li>
<li class="chapter" data-level="4.9" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-t-de-student"><i class="fa fa-check"></i><b>4.9</b> Exemplo de aplicação do teste t de Student</a></li>
<li class="chapter" data-level="4.10" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-tukey"><i class="fa fa-check"></i><b>4.10</b> Teste de Tukey</a></li>
<li class="chapter" data-level="4.11" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-tukey"><i class="fa fa-check"></i><b>4.11</b> Exemplo de aplicação do teste de Tukey</a></li>
<li class="chapter" data-level="4.12" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-duncan"><i class="fa fa-check"></i><b>4.12</b> Teste de Duncan</a></li>
<li class="chapter" data-level="4.13" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-duncan"><i class="fa fa-check"></i><b>4.13</b> Exemplo de aplicação do teste de Duncan</a></li>
<li class="chapter" data-level="4.14" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-scheffé"><i class="fa fa-check"></i><b>4.14</b> Teste de Scheffé</a></li>
<li class="chapter" data-level="4.15" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-scheffé"><i class="fa fa-check"></i><b>4.15</b> Exemplo de aplicação do teste de Scheffé</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html"><i class="fa fa-check"></i><b>5</b> DELINEAMENTO INTEIRAMENTE CASUALIZADO</a><ul>
<li class="chapter" data-level="5.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#caracterização"><i class="fa fa-check"></i><b>5.1</b> Caracterização</a></li>
<li class="chapter" data-level="5.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático"><i class="fa fa-check"></i><b>5.2</b> Modelo Matemático</a></li>
<li class="chapter" data-level="5.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#hipóteses-básicas-para-aplicação-da-análoise-de-variância"><i class="fa fa-check"></i><b>5.3</b> Hipóteses básicas para aplicação da análoise de variância</a></li>
<li class="chapter" data-level="5.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>5.4</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="5.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>5.5</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><i class="fa fa-check"></i><b>6</b> DELINEAMENTO INTEIRAMENTE CASUALIZADO COM NÚMERO DIFERENTE DE REPETIÇÕES POR TRATAMENTO</a><ul>
<li class="chapter" data-level="6.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>6.1</b> Introdução</a></li>
<li class="chapter" data-level="6.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>6.2</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="6.3" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-das-médias-e-error-padrôes-das-médias"><i class="fa fa-check"></i><b>6.3</b> Cálculo das médias e error padrôes das médias</a></li>
<li class="chapter" data-level="6.4" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#teste-de-tukey-para-comparação-das-médias"><i class="fa fa-check"></i><b>6.4</b> Teste de Tukey para comparação das médias</a></li>
<li class="chapter" data-level="6.5" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>6.5</b> Cálculo do coeficiente de variação do experimento</a></li>
<li class="chapter" data-level="6.6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#aplicação-do-teste-t-de-student-a-um-contraste"><i class="fa fa-check"></i><b>6.6</b> Aplicação do teste t de Student a um contraste</a></li>
<li class="chapter" data-level="6.7" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#teste-de-duncan-para-a-comparação-das-médias"><i class="fa fa-check"></i><b>6.7</b> Teste de Duncan para a comparação das médias</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><i class="fa fa-check"></i><b>7</b> DESDOBRAMENTO DE GRAUS DE LIBERDADE DE TRATAMENTOS</a><ul>
<li class="chapter" data-level="7.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>7.1</b> Introdução</a></li>
<li class="chapter" data-level="7.2" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#obtenção-da-análise-de-variância-com-desdobramento-dos-graus-de-liberdade-de-tratamentos"><i class="fa fa-check"></i><b>7.2</b> Obtenção da análise de variância com desdobramento dos graus de liberdade de tratamentos</a></li>
<li class="chapter" data-level="7.3" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#método-dos-contrastes-de-totais-de-tratamentos"><i class="fa fa-check"></i><b>7.3</b> Método dos contrastes de totais de tratamentos</a></li>
<li class="chapter" data-level="7.4" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#método-dos-totais-de-tratamentos-sem-utilizar-contrastes"><i class="fa fa-check"></i><b>7.4</b> Método dos totais de tratamentos (sem utilizar contrastes)</a></li>
<li class="chapter" data-level="7.5" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#análise-de-variância-com-desdobramento-dos-graus-de-liberdade-de-tratamentos"><i class="fa fa-check"></i><b>7.5</b> Análise de variância com desdobramento dos graus de liberdade de tratamentos</a><ul>
<li class="chapter" data-level="7.5.1" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#conclusões"><i class="fa fa-check"></i><b>7.5.1</b> <strong>Conclusões</strong></a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#componentes-com-maisde-um-grau-de-liberdade"><i class="fa fa-check"></i><b>7.6</b> Componentes com maisde um grau de liberdade</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="delineamento-em-blocos-casualizados.html"><a href="delineamento-em-blocos-casualizados.html"><i class="fa fa-check"></i><b>8</b> DELINEAMENTO EM BLOCOS CASUALIZADOS</a><ul>
<li class="chapter" data-level="8.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#caracterização"><i class="fa fa-check"></i><b>8.1</b> Caracterização</a></li>
<li class="chapter" data-level="8.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático"><i class="fa fa-check"></i><b>8.2</b> Modelo matemático</a></li>
<li class="chapter" data-level="8.3" data-path="delineamento-em-blocos-casualizados.html"><a href="delineamento-em-blocos-casualizados.html#hipóteses-básicas"><i class="fa fa-check"></i><b>8.3</b> Hipóteses básicas</a></li>
<li class="chapter" data-level="8.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>8.4</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="8.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>8.5</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><i class="fa fa-check"></i><b>9</b> DELINEAMENTO EM BLOCOS CASUALIZADOS COM UMA PARCELA PERDIDA</a><ul>
<li class="chapter" data-level="9.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>9.1</b> Introdução</a></li>
<li class="chapter" data-level="9.2" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#estimativa-da-parcela-perdida"><i class="fa fa-check"></i><b>9.2</b> Estimativa da parcela perdida</a></li>
<li class="chapter" data-level="9.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>9.3</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="9.4" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#médias-de-tratamentos"><i class="fa fa-check"></i><b>9.4</b> Médias de tratamentos</a></li>
<li class="chapter" data-level="9.5" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#erros-padrões-das-médias"><i class="fa fa-check"></i><b>9.5</b> Erros padrões das médias</a></li>
<li class="chapter" data-level="9.6" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#comparação-de-médias-pelo-teste-de-tukey"><i class="fa fa-check"></i><b>9.6</b> Comparação de médias pelo teste de Tukey</a></li>
<li class="chapter" data-level="9.7" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>9.7</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html"><i class="fa fa-check"></i><b>10</b> EXPERIMENTOS FATORIAIS</a><ul>
<li class="chapter" data-level="10.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>10.1</b> Introdução</a></li>
<li class="chapter" data-level="10.2" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-simples-de-um-fator"><i class="fa fa-check"></i><b>10.2</b> Efeito simples de um fator</a></li>
<li class="chapter" data-level="10.3" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-principal-de-um-fator"><i class="fa fa-check"></i><b>10.3</b> Efeito principal de um fator</a></li>
<li class="chapter" data-level="10.4" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-da-interação-entre-fatores"><i class="fa fa-check"></i><b>10.4</b> Efeito da interação entre fatores</a></li>
<li class="chapter" data-level="10.5" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#vantagens-dos-experimentos-fatoriais"><i class="fa fa-check"></i><b>10.5</b> Vantagens dos experimentos fatoriais</a></li>
<li class="chapter" data-level="10.6" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#desvantagens-dos-experimentos-fatoriais"><i class="fa fa-check"></i><b>10.6</b> Desvantagens dos experimentos fatoriais</a></li>
<li class="chapter" data-level="10.7" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#classificação-dos-experementos-fatoriais"><i class="fa fa-check"></i><b>10.7</b> Classificação dos Experementos Fatoriais</a></li>
<li class="chapter" data-level="10.8" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#casualização-dos-tratamentos"><i class="fa fa-check"></i><b>10.8</b> Casualização dos tratamentos</a></li>
<li class="chapter" data-level="10.9" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#análise-de-variância-de-um-experimento-fatorial-com-2-fatores-com-interação-não-significativa"><i class="fa fa-check"></i><b>10.9</b> Análise de variância de um experimento fatorial com 2 fatores com interação não significativa</a></li>
<li class="chapter" data-level="10.10" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>10.10</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="10.11" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#cálculo-das-média-de-tratamento-do-solo-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>10.11</b> Cálculo das média de Tratamento do Solo e erros padrões das médias</a></li>
<li class="chapter" data-level="10.12" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#cálculo-das-média-de-fungicidas-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>10.12</b> Cálculo das média de Fungicidas e erros padrões das médias</a></li>
<li class="chapter" data-level="10.13" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>10.13</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><i class="fa fa-check"></i><b>11</b> ANÁLISE DE UM EXPERIMENTO FATORIAL COM 2 FATORES, COM INTERAÇÃO SIGNIFICATIVA</a><ul>
<li class="chapter" data-level="11.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>11.1</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="11.2" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#desdobrando-a-interação-itimes-d-para-estudar-os-efeitos-do-fator-doses-em-cada-nível-do-fator-inseticida-d-d.-i"><i class="fa fa-check"></i><b>11.2</b> Desdobrando a interação <span class="math inline">\(I\times D\)</span>, para estudar os efeitos do fator <strong>DOSES</strong> em cada nível do fator <strong>INSETICIDA</strong> (D d. I):</a></li>
<li class="chapter" data-level="11.3" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#desdobrando-a-interação-i-times-d-para-estudar-os-efeitos-do-fator-inseticidas-dentro-de-cada-nível-do-fator-dose-d-d.-i"><i class="fa fa-check"></i><b>11.3</b> Desdobrando a interação <span class="math inline">\(I \times D\)</span>, para estudar os efeitos do fator <strong>INSETICIDAS</strong> dentro de cada nível do fator <strong>DOSE</strong> (D d. I):</a></li>
<li class="chapter" data-level="11.4" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#teste-de-tukey-para-a-comparação-de-médias"><i class="fa fa-check"></i><b>11.4</b> Teste de Tukey para a comparação de médias</a></li>
<li class="chapter" data-level="11.5" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#para-comparar-médias-de-inseticidas-na-dose-1-i-d.-d_1"><i class="fa fa-check"></i><b>11.5</b> Para comparar médias de Inseticidas na Dose 1 (I d. <span class="math inline">\(D_1\)</span>)</a></li>
<li class="chapter" data-level="11.6" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#para-comparar-médias-de-inseticidas-na-dose-2-i-d.-d_2"><i class="fa fa-check"></i><b>11.6</b> Para comparar médias de Inseticidas na Dose 2 (I d. <span class="math inline">\(D_2\)</span>)</a></li>
<li class="chapter" data-level="11.7" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>11.7</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html"><i class="fa fa-check"></i><b>12</b> Estudo do Fatorial <span class="math inline">\(3^2\)</span></a><ul>
<li class="chapter" data-level="12.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>12.1</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="12.2" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#desdobrando-a-interação-etimes-d-para-estudar-os-efeitos-do-fator-espaçamento-em-cada-nível-do-fator-densidade-e-d.-d"><i class="fa fa-check"></i><b>12.2</b> Desdobrando a interação <span class="math inline">\(E\times D\)</span>, para estudar os efeitos do fator <strong>Espaçamento</strong> em cada nível do fator <strong>Densidade</strong> (E d. D):</a></li>
<li class="chapter" data-level="12.3" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#desdobrando-a-interação-etimes-d-para-estudar-os-efeitos-do-fator-densidade-em-cada-nível-do-fator-espaçamentos-d-d.-e"><i class="fa fa-check"></i><b>12.3</b> Desdobrando a interação <span class="math inline">\(E\times D\)</span>, para estudar os efeitos do fator <strong>Densidade</strong> em cada nível do fator <strong>Espaçamentos</strong> (D d. E):</a></li>
<li class="chapter" data-level="12.4" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#teste-de-tukey-para-a-comparação-de-médias"><i class="fa fa-check"></i><b>12.4</b> Teste de Tukey para a comparação de médias</a></li>
<li class="chapter" data-level="12.5" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#resultado-do-teste-de-tukey"><i class="fa fa-check"></i><b>12.5</b> Resultado do teste de Tukey</a></li>
<li class="chapter" data-level="12.6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>12.6</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html"><i class="fa fa-check"></i><b>13</b> Estudo do Fatorial <span class="math inline">\(2^3\)</span></a><ul>
<li class="chapter" data-level="13.1" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#análise-de-variância-de-um-experimento-fatorial-23"><i class="fa fa-check"></i><b>13.1</b> Análise de variância de um experimento fatorial <span class="math inline">\(2^3\)</span></a></li>
<li class="chapter" data-level="13.2" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-das-somas-de-quadrados-pelo-método-dos-contrastes-de-totais-de-tratamentos."><i class="fa fa-check"></i><b>13.2</b> Cálculo das somas de quadrados pelo método dos contrastes de totais de tratamentos.</a></li>
<li class="chapter" data-level="13.3" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#desdobramento-da-interação-n-times-k"><i class="fa fa-check"></i><b>13.3</b> Desdobramento da Interação <span class="math inline">\(N \times K\)</span></a></li>
<li class="chapter" data-level="13.4" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-das-médias-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>13.4</b> Cálculo das médias e erros padrões das médias</a></li>
<li class="chapter" data-level="13.5" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-do-coeficiente-de-variação"><i class="fa fa-check"></i><b>13.5</b> Cálculo do coeficiente de variação</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html"><i class="fa fa-check"></i><b>14</b> Experimentos em Parcelas Subdivididas</a><ul>
<li class="chapter" data-level="14.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>14.1</b> Introdução</a></li>
<li class="chapter" data-level="14.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>14.2</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="14.3" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#desdobramento-da-interação-e-times-v-para-estudar-os-efeitos-de-variedades-dentro-de-cada-época-de-plantio-v-d.-e"><i class="fa fa-check"></i><b>14.3</b> 1. Desdobramento da interação E <span class="math inline">\(\times\)</span> V para estudar os efeitos de Variedades dentro de cada Época de plantio (V d. E):</a></li>
<li class="chapter" data-level="14.4" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#desdobramento-da-interação-e-times-v-para-estudar-os-efeitos-de-épocas-dentro-de-cada-variedade-e-d.-v"><i class="fa fa-check"></i><b>14.4</b> 2. Desdobramento da interação E <span class="math inline">\(\times\)</span> V para estudar os efeitos de Épocas dentro de cada Variedade (E d. V):</a></li>
<li class="chapter" data-level="14.5" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-das-médias"><i class="fa fa-check"></i><b>14.5</b> Cálculo das médias</a></li>
<li class="chapter" data-level="14.6" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-dos-erros-padrões"><i class="fa fa-check"></i><b>14.6</b> Cálculo dos erros padrões:</a></li>
<li class="chapter" data-level="14.7" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-dos-coeficientes-de-variação-do-experimento"><i class="fa fa-check"></i><b>14.7</b> Cálculo dos coeficientes de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html"><i class="fa fa-check"></i><b>15</b> Análise de Regressão por Polinômios Ortogonais</a><ul>
<li class="chapter" data-level="15.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>15.1</b> Introdução</a></li>
<li class="chapter" data-level="15.2" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#obtenção-da-análise-de-variância-estudando-se-os-efeitos-da-regressão"><i class="fa fa-check"></i><b>15.2</b> Obtenção da análise de variância, estudando-se os efeitos da regressão</a></li>
<li class="chapter" data-level="15.3" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#coeficientes-de-interpolação-de-polinômios-ortogonais"><i class="fa fa-check"></i><b>15.3</b> Coeficientes de interpolação de polinômios ortogonais</a></li>
<li class="chapter" data-level="15.4" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#obtendo-a-equação-de-regressão"><i class="fa fa-check"></i><b>15.4</b> Obtendo a Equação de Regressão</a></li>
<li class="chapter" data-level="15.5" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cálculo-do-coeficiente-de-determinação-r²"><i class="fa fa-check"></i><b>15.5</b> Cálculo do Coeficiente de Determinação (R²)</a></li>
<li class="chapter" data-level="15.6" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#gráfico-da-regressão-ajustada"><i class="fa fa-check"></i><b>15.6</b> Gráfico da Regressão Ajustada</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso do R do GIEU</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análise-de-regressão-por-polinômios-ortogonais" class="section level1">
<h1><span class="header-section-number">Capítulo 15</span> Análise de Regressão por Polinômios Ortogonais</h1>
<div id="introdução" class="section level2">
<h2><span class="header-section-number">15.1</span> Introdução</h2>
<p>Nos experimentos em que os tratamentos são quantitativos, como por exemplo, níveis crescentes de um adubo, doses crescentes de um inseticida, etc, muitas vezes existe uma correspondência funcional, denominada equação de regressão, que relaciona os valores dos tratamentos (X) com os dados analisados (Y).</p>
<p>Por exemplo, essa dependência pode ser notada no caso seguinte,onde X representa oas doses de um adubo (<span class="math inline">\(kg\;h^{-1}\)</span>) e y a produção de milho (<span class="math inline">\(kg\;h^{-1}\)</span>).</p>
<table>
<thead>
<tr class="header">
<th align="center">X</th>
<th align="center">0</th>
<th align="center">25</th>
<th align="center">50</th>
<th align="center">75</th>
<th align="center">100</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Y</td>
<td align="center">2100</td>
<td align="center">2600</td>
<td align="center">3000</td>
<td align="center">3550</td>
<td align="center">4150</td>
</tr>
</tbody>
</table>
<p>Verificamos, portanto ,que há uma tendência de aumento na produção à medida que aumentamos a quantidade de adubo aplicada.</p>
<p>Vejamos então, como fazer a análise de variância para o estudo da regressão. O método utilizado é denominado de método dos polinômios ortogonais, e é de fácil aplicação quanto os níveis de X são equidistantes, poixs permitem a utilização de coeficientes obtidos em tabelas.</p>
</div>
<div id="obtenção-da-análise-de-variância-estudando-se-os-efeitos-da-regressão" class="section level2">
<h2><span class="header-section-number">15.2</span> Obtenção da análise de variância, estudando-se os efeitos da regressão</h2>
<p>Para estudo da regressão, vamos utilizar os dados do trabalho: “Efeito de doses de gesso na cultura do feijoeiro (<em>Phaseolu vulgaris</em> L.)”, realizado por RAGAZZI (1979). Neste trabalho foram utilizadas 7 doses de gesso 0, 50, 100, 150, 200, 250, e 300 <span class="math inline">\(kg\;ha^{-1}\)</span>. Os resultados obtidos para peso de 1000 sementes, em gramas, são apresentados a seguir:</p>
<table>
<thead>
<tr class="header">
<th>Tratamentos</th>
<th align="center">Rep. 1|</th>
<th align="center">Rep. 2</th>
<th align="center">Rep. 3</th>
<th align="center">Rep. 4</th>
<th align="center">Totais</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td align="center">134.8| 13</td>
<td align="center">139.7|</td>
<td align="center">147.6|</td>
<td align="center">132.3|</td>
<td align="center">554.4|</td>
</tr>
<tr class="even">
<td>50</td>
<td align="center">161.7| 1</td>
<td align="center">157.7 |15</td>
<td align="center">150.3</td>
<td align="center">144.7 |6</td>
<td align="center">614.4</td>
</tr>
<tr class="odd">
<td>100</td>
<td align="center">160.7 |172</td>
<td align="center">172.7 |</td>
<td align="center">163.4</td>
<td align="center">161.3 |6</td>
<td align="center">658.1</td>
</tr>
<tr class="even">
<td>150</td>
<td align="center">169.8 |168</td>
<td align="center">168.2 |</td>
<td align="center">160.7</td>
<td align="center">161.0 |6</td>
<td align="center">659.7</td>
</tr>
<tr class="odd">
<td>200</td>
<td align="center">165.7 |160</td>
<td align="center">160.0 |</td>
<td align="center">158.2</td>
<td align="center">151.0 |6</td>
<td align="center">634.9</td>
</tr>
<tr class="even">
<td>250</td>
<td align="center">171.8 |157</td>
<td align="center">157.3 |</td>
<td align="center">150.4</td>
<td align="center">160.4 |6</td>
<td align="center">639.9</td>
</tr>
<tr class="odd">
<td>300</td>
<td align="center">154.5 |160</td>
<td align="center">160.4 |</td>
<td align="center">148.8</td>
<td align="center">154.0</td>
<td align="center">617.7|</td>
</tr>
<tr class="even">
<td>Totais</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center">4379.1</td>
</tr>
</tbody>
</table>
<p>A análise de variância preliminar será realizada de acordo com o delineamento experimental utilizado. O Ensaio foi montado de acordo com o delineamento inteiramente casualizado, e portanto, a análise de variância preliminar, obtido de maneira usual, foi a seguinte:
<span class="math display">\[
SQ_{Total} = (134.8^2+139.7^2+\cdots+154.0^2)-\frac{4379.1^2}{7\cdot4}=2828.17 \\
\\
SQ_{Trat}=\frac{1}{4}[554.4^2+614.4^2+\cdots+617.7^2]-\frac{4379.1^2}{7\cdot4} = 1941.83 \\
\\
SQ_{Res} = SQ_{Total}-SQ_{Trat}=2828.17-1941.83=886.34
\]</span></p>
<p>Quadro de análise de variância preliminar:</p>
<table>
<thead>
<tr class="header">
<th align="center">Causas de Variação</th>
<th align="center">GL</th>
<th align="center">SQ</th>
<th align="center">QM</th>
<th align="center">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Tratamentos</td>
<td align="center">6</td>
<td align="center">1941.83</td>
<td align="center">323.64</td>
<td align="center">7.67**</td>
</tr>
<tr class="even">
<td align="center">Resíduo</td>
<td align="center">21</td>
<td align="center">886.34</td>
<td align="center">42.21</td>
<td align="center">–</td>
</tr>
<tr class="odd">
<td align="center"><strong>Total</strong></td>
<td align="center"><strong>27</strong></td>
<td align="center"><strong>2828.17</strong></td>
<td align="center"><strong>–</strong></td>
<td align="center"><strong>–</strong></td>
</tr>
</tbody>
</table>
<p><strong>Conclusão</strong>: O teste F foi significativo ao nível de <span class="math inline">\(1\%\)</span> de probabilidade, logo, rejeitamos a hipótese da nulidade (<span class="math inline">\(H_0\)</span>), e concluímos que as doses de gesso aplicadas possuem efeitos diferentes sobre o peso de 1000 sementes.</p>
<p>No entanto, um caso como este, em que os tratamentos são quantitativos, e em mais de 2 níveis, uma análise mais detalhada deve levar em conta a regressão, desdobrando-se os 6 graus de liberdade de tratamentos em:</p>
<p>Regressão Linear……..1 GL<br />
Regressão Quadrática…1 GL<br />
Regressão Cúbica……..1 GL<br />
Regressão de 4º grau…1 GL<br />
Regressão de 5º grau…1 GL<br />
Regressão de 6º grau…1 GL<br />
—————————————<br />
(Tratamentos)…………(6) GL</p>
<p>Porém, as regressões de grau maior que 3º não tem interesse prático, de modo que, na análise de variância, podemos considerar as regress~es de graus maior que o 3º como uma única causa de variação, que denominamos de <strong>Desvios da Regressão</strong>. Assim, no nosso exemplo, temos:</p>
<table>
<thead>
<tr class="header">
<th align="left">Causas de Variação</th>
<th align="right">GL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Regressão Linear</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Regressão Quadrática</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">Regressão Cúbica</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Desvios da Regressão</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="left">(Tratamentos)</td>
<td align="right">(6)</td>
</tr>
<tr class="even">
<td align="left">Resíduo</td>
<td align="right">21</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="right">27</td>
</tr>
</tbody>
</table>
<p>Esta decomposição pode ser feita pelo métido dos polinômios ortogoais, e é de fácil aplicação quando as quantidades que determinam os tratamentos são igualmente espaçadas (equidistantes), o que ocorre no caso em estudo (0, 50, 100, 150, 20, 250, 300). Neste casos, os coeficientes dos polinômios ortogonais são obtidos em tabelas, como a seguintes:</p>
</div>
<div id="coeficientes-de-interpolação-de-polinômios-ortogonais" class="section level2">
<h2><span class="header-section-number">15.3</span> Coeficientes de interpolação de polinômios ortogonais</h2>
<p><img src="Tpoli01.png" /></p>
<p><img src="Tpoli02.png" /></p>
<p><span class="math display">\[
\begin{align}
&amp; P_1 = x\;\;\;\;\;\;\;\;\;\;\;P_2=x^2-\frac{n^2-1}{12}\;\;\;\;\;\;\;\;\;\;\;P_3=x^3-\frac{3n^2-7}{20}x \\
\\
&amp; onde, \\ \\
&amp; x=\frac{X-\bar{X}}{q}
\end{align}
\]</span></p>
<p>Para facilitar os cálculos, montamos o quadro seguinte, onde aparecem os totais de tratamentos (<span class="math inline">\(T_i\)</span>) e os coeficientes dos polinômios ortogonais (<span class="math inline">\(C_{ji}\)</span>) para cada componente:</p>
<p>No nosso exemplo, utilizaremos os coeficientes para n=7 níveis:</p>
<p><img src="Tpoli03.png" /></p>
<p>Com este coeficientes (<span class="math inline">\(C_{ji}\)</span>) e Totais (<span class="math inline">\(T_i\)</span>), estabelecemos contrastes ortogonais, sendo um contraste para o efeito da Regressão Linear (1º grau), outro para a refressão Quadrática (2º grau) e outro para a Regressão Cúbica (3º grau).</p>
<p>As tabelas de coeficientes dos polinômios ortogonais nos fornecem ainda, a soma dos quadrados dos coeficientes (<strong>K</strong>), e uma constante (<strong>M</strong>) que deverá ser utilizada na determinação da equação de regressão.</p>
<p>Então, o contraste correspondente à regressão de grau j será:</p>
<p><span class="math display">\[
Y_{Grau\;j} = \sum_{i=1}^IC_{ji}T_{i}
\]</span></p>
<p>E a soma de quadrados correspondente, será:</p>
<p><span class="math display">\[
SQ_{Reg.Grau\;j} = \frac{\hat{Y}_{Grau\;j}^2}{r\cdot K_j}
\]</span></p>
<p>onde,</p>
<p><span class="math inline">\(\hat{Y}_{Grau\;j}\)</span> = Estimativa do conraste para a regressão de grau <em>j</em>.</p>
<p><span class="math inline">\(r\)</span>=número de repetições com que foram calculados os totais <span class="math inline">\(T_i\)</span>.</p>
<p><span class="math inline">\(K_j=\sum_{i=1}^IC_{ji}^2\)</span> = soma dos quadrado dos coeficientes do contraste para a regressão de grau <em>j</em>.</p>
<p>Portanto, no nosso exemplo, temos:</p>
<ol style="list-style-type: lower-alpha">
<li>Regressão Linear ou de Grau 1:</li>
</ol>
<p><span class="math display">\[
\begin{align}
&amp; Y_{\text{Reg. Linear}} = \sum_{i=1}^IC_{1i}T_i=-3T_1-2T_2-1T_3+0T_4+1T_5+2T_6+3T_7 \\
&amp; \hat{Y}_{\text{Reg. Linear}} = -3(554.4)-2(614.4)-1(658.1)+0(659.7)+1(634.9)+2(639.9)+3(617.7) \\
&amp; \hat{Y}_{\text{Reg. Linear}} = 217.7\;g \\
&amp; SQ_{Reg.Linear}=\frac{\hat{Y}_{\text{Reg. Linear}}^2}{r\cdot K_1}=\frac{217.7^2}{4\cdot28}=423.15
\end{align}
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Regressão Quadrádica ou de Grau 2:</li>
</ol>
<p><span class="math display">\[
\begin{align}
&amp; Y_{\text{Reg.Quadrática}} = \sum_{i=1}^IC_{2i}T_i=5T_1+0T_2-3T_3-4T_4-3T_5+0T_6+5T_7 \\
&amp; \hat{Y}_{\text{Reg.Quadrática}} = 5(554.4)+0(614.4)-3(658.1)-4(659.7)-3(634.9)+0(639.9)+5(617.7) \\
&amp; \hat{Y}_{\text{Reg.Quadrática}} = -657.3\;g \\
&amp; SQ_{Reg.Quadrática}=\frac{\hat{Y}_{\text{Grau.2}}^2}{r\cdot K_2}=\frac{(-657.3)^2}{4\cdot84}=1285.84
\end{align}
\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Regressão Cúbica ou de Grau 3:</li>
</ol>
<p><span class="math display">\[
\begin{align}
&amp; Y_{\text{Reg.Cúbica}} = \sum_{i=1}^IC_{3i}T_i=-1T_1+1T_2+1T_3+0T_4-1T_5-1T_6+1T_7 \\
&amp; \hat{Y}_{\text{Reg.Cúbica}} = -1(554.4)+1(614.4)+1(658.1)+0(659.7)-1(634.9)-1(639.9)+1(617.7) \\
&amp; \hat{Y}_{\text{Reg.Cúbica}} = 61.0\;g \\
&amp; SQ_{Reg.Cúbica}=\frac{\hat{Y}_{\text{Grau.3}}^2}{r\cdot K_3}=\frac{155.04^2}{4\cdot6}=155.04
\end{align}
\]</span>
d) Desvios da Regressão:</p>
<p><span class="math display">\[
SQ_{Desvios\;da\;Regressão}= SQ_{Trat.}-SQ_{Reg.Linear}-SQ_{Reg.Quadrática}-SQ_{Reg.Cúbica} \\
SQ_{Desvios\;da\;Regressão}= 1941.83-423.15-1285.84-155.04 \\
SQ_{Desvios\;da\;Regressão}= 77.80
\]</span></p>
<p>Com estas somas de quadrado, podemos montar</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Causas de Variação
</th>
<th style="text-align:left;">
GL
</th>
<th style="text-align:left;">
SQ
</th>
<th style="text-align:left;">
QM
</th>
<th style="text-align:left;">
F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Regressão Linear
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
423.15
</td>
<td style="text-align:left;">
423.15
</td>
<td style="text-align:left;">
10.02**
</td>
</tr>
<tr>
<td style="text-align:left;">
Regressão Quadrática
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1285.84
</td>
<td style="text-align:left;">
1285.84
</td>
<td style="text-align:left;">
30.46**
</td>
</tr>
<tr>
<td style="text-align:left;">
Regressão Cúbica
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
155.04
</td>
<td style="text-align:left;">
155.04
</td>
<td style="text-align:left;">
3,67
</td>
</tr>
<tr>
<td style="text-align:left;">
Desvios da Regressão
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
77.80
</td>
<td style="text-align:left;">
25.93
</td>
<td style="text-align:left;">
0.61
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
(Tratamentos)
</td>
<td style="text-align:left;font-weight: bold;">
6
</td>
<td style="text-align:left;font-weight: bold;">
(1941.83)
</td>
<td style="text-align:left;font-weight: bold;">
–
</td>
<td style="text-align:left;font-weight: bold;">
–
</td>
</tr>
<tr>
<td style="text-align:left;">
Resíduo
</td>
<td style="text-align:left;">
21
</td>
<td style="text-align:left;">
886.34
</td>
<td style="text-align:left;">
42.21
</td>
<td style="text-align:left;">
–
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Total
</td>
<td style="text-align:left;font-weight: bold;">
27
</td>
<td style="text-align:left;font-weight: bold;">
2828.17
</td>
<td style="text-align:left;font-weight: bold;">
–
</td>
<td style="text-align:left;font-weight: bold;">
–
</td>
</tr>
</tbody>
</table>
<p>Valores de F da tabela (<span class="math inline">\(1\times21GL\)</span>): <span class="math inline">\(\begin{cases} 5\%=4.32 \\ 1\%=8.02 \end{cases}\)</span></p>
<p>Valores de F da tabela (<span class="math inline">\(3\times21GL\)</span>): <span class="math inline">\(\begin{cases} 5\%=3.07 \\ 1\%=4.87 \end{cases}\)</span></p>
<p><strong>CONCLUSÃO</strong>:<br />
Os testes F para a regressão linear e regressão quadrática foram significativos ao nível de <span class="math inline">\(1\%\)</span> de probabilidade, indicando que é possível estabelecer uma relação funcional entre a dose de gesso (<span class="math inline">\(X\)</span>) e o peso de 1000 sementes do feijoeiro (<span class="math inline">\(Y\)</span>).</p>
<p>A equação de regressão que melhor se ajusta aos dados é a correspondente à <strong>REGRESSÃO DE MAIS ALTO GRAU</strong> cujo teste F soi significativo.</p>
<p>Assim, sendo, no nosso exemplo, a equação que melhor se ajusta é a de 2º grau (Quadrática).</p>
<p>Quando o teste F para <strong>Desvios da Regressão for significativo</strong>, isto indica que <strong>existe alguma regressão significativa de grau maior que o 3º</strong> e, se tivermos interesse em estudá-la, devemos desdobrar os graus de liberdade de Desvio da Regressão.</p>
</div>
<div id="obtendo-a-equação-de-regressão" class="section level2">
<h2><span class="header-section-number">15.4</span> Obtendo a Equação de Regressão</h2>
<p>A equação de regressão, até um certo grau <span class="math inline">\(p\)</span>, tem a seguinte expressão:</p>
<p><span class="math display">\[
\hat{Y}=\bar{Y}+\hat{b}_1M_1P_1+\hat{b}_2M_2P_2+\cdots+\hat{b}_pM_pP_p
\]</span></p>
<p>onde:</p>
<p><span class="math display">\[
\bar{Y}=\frac{\sum_{i=1}^IT_i}{I\cdot r}=\frac{G}{I \cdot r} \\ 
\\
\hat{b}_1=\frac{\sum_{i=1}^IC_{1i}T_i}{r \cdot K_1} = \frac{\hat{Y}_{Reg.Linear}}{r \cdot K_1} \\
\\
\hat{b}_2=\frac{\sum_{i=1}^IC_{2i}T_i}{r \cdot K_2} = \frac{\hat{Y}_{Reg.Quadrática}}{r \cdot K_2} \\
\\
\cdots
\\
\hat{b}_p=\frac{\sum_{i=1}^IC_{pi}T_i}{r \cdot K_p} = \frac{\hat{Y}_{Reg.Grau\;p}}{r \cdot K_p}
\]</span></p>
<p>e os <span class="math inline">\(P_j\)</span> são os polinômios ortogonais expressos literalmente em relação à <span class="math inline">\(x\)</span> (obtidos em tabelas):</p>
<p><span class="math display">\[
P_1 = x\;\;\;\;\;\;\;\;\;\;\;P_2=x^2-\frac{n^2-1}{12}\;\;\;\;\;\;\;\;\;\;\;P_3=x^3-\frac{3n^2-7}{20}x \\
\]</span></p>
<p>No nosso exemplo o teste F indicou que a equação que melhor se ajusta aos dados é a do 2º grau, e portanto, temos:</p>
<p><span class="math display">\[
\bar{Y}=\frac{\sum_{i=1}^IT_i}{I\cdot r}=\frac{4379.1}{7 \cdot 4}=156.3964 \\
\hat{b}_1= \frac{\hat{Y}_{Reg.Linear}}{r \cdot K_1}=\frac{217.7}{4\cdot28}=1.9438 \\
M_1 = 1 \\
P_1=x\\
\hat{b}_2= \frac{\hat{Y}_{Reg.Quadrática}}{r \cdot K_2}=\frac{-657.3}{4\cdot84}=-1.9563 \\
M_2 = 1 \\
P_2=x^2-\frac{n^2-1}{12} \text{, onde }n\text{ = nº de níveis de X.} \\
\]</span>
No exemplo, temos 7 níveis de X, e portanto, o valor de <span class="math inline">\(P_2\)</span> será:</p>
<p><span class="math display">\[
P_2=x^2-\frac{7^2-1}{12}=x^2-4
\]</span></p>
<p>Então, a equação de regressão será:</p>
<p><span class="math display">\[
\hat{Y}=\bar{Y}+\hat{b}_1M_1P_1+\hat{b}_2M_2P_2 \\
\hat{Y}=156.3964+1.9438x-1.9563(x^2-4) \\
\hat{Y}= 164.2216+1.9438x-1.9563x^2
\]</span></p>
<p>Esta equação foi obtida utilizando-se, para facilitar os cálculos, uma variável auxiliar:</p>
<p><span class="math inline">\(x=\frac{X-\bar{X}}{q}\)</span>, onde <span class="math inline">\(\bar{X}\)</span> é a média dos valores de <span class="math inline">\(X\)</span> e <span class="math inline">\(q\)</span> é a diferença entre dois níveis consecutivos de X.</p>
<p>Assim sendo, devemos expressar a equação de regressão em função de X. No noso exemplo, temos:</p>
<p><span class="math display">\[
\bar{X}=\frac{0+50+100+150+200+250+300}{7}=150 \\
q=50
\]</span>
Então,</p>
<p><span class="math inline">\(x=\frac{X-150}{50}\)</span></p>
<p>Substituindo-se a expressão de <span class="math inline">\(x\)</span> na equação de regressão, teremos</p>
<p><span class="math display">\[
\hat{Y}= 164.2216+1.9438  \left( \frac{X-150}{50} \right) -1.9563 \left(\frac{X-150}{50}\right)^2 \\
\hat{Y}= 164.2216+1.9438  \left( \frac{X-150}{50} \right) -1.9563 \left(\frac{X^2-300X+150^2}{50^2}\right) \\
\hat{Y}= 164.2216+0.0389X-5.8314-0.000783X^2+0.2348X-17.6067 \\
\hat{Y}= 140.7835+0.2737X-0.000783X^2, \;para\;0 \leq X \leq 300
\]</span></p>
<p>onde,
<span class="math inline">\(\hat{Y}\)</span> é o Peso de 1000 sementes (<span class="math inline">\(g\)</span>).</p>
<p><span class="math inline">\(X\)</span> é a dose de gesso aplicada (<span class="math inline">\(kg\;ha^{-1}\)</span>).</p>
</div>
<div id="cálculo-do-coeficiente-de-determinação-r²" class="section level2">
<h2><span class="header-section-number">15.5</span> Cálculo do Coeficiente de Determinação (R²)</h2>
<p>O coeficiente de determinação fornece uma medida do grau de ajuste da equação de regressão estimada. Ele varia entre 0 e 1 e quanto mais próximo de 1 maior o grau de ajuste da equação de regressão estimada. O valor do coeficiente de determinação para uma regressão polinomial de grau p, pode ser obitido por:</p>
<p><span class="math display">\[
R^2= \frac{SQ_{Reg.Grau\;1}+SQ_{Reg.Grau\;2}+\cdots+SQ_{reg.Grau\;p}}{SQ_{Trat}}
\]</span>
então, como nosso exemplo, a equação ajustada foi do segundo grau, portanto, o coeficiente de determinação será:</p>
<p><span class="math display">\[
R^2= \frac{SQ_{Reg.Grau\;1}+SQ_{Reg.Grau\;2}}{SQ_{Trat}}=\frac{423.15+1285.84}{1941.83} =0.8801
\]</span></p>
<p>Portanto, <span class="math inline">\(88.01\%\)</span> da variação do peso de 1000 sementes é explicada pela regressão do peso de 1000 sementes em função da dose de gesso aplicada.</p>
</div>
<div id="gráfico-da-regressão-ajustada" class="section level2">
<h2><span class="header-section-number">15.6</span> Gráfico da Regressão Ajustada</h2>
<p>Podemos fazer uma verificação do ajuste da equação de regressão, calculando os valores esperados de (<span class="math inline">\(\hat{Y}_i\)</span>) por meio da equação de regressão ajustada, e os valores observados (<span class="math inline">\(\bar{Y}_{i\;Obs}\)</span>) por meio das médias dos tratamentos.</p>
<p>Devemos verificar que <span class="math inline">\(\sum_{i=1}^I\bar{Y}_{i~Obs}=\sum_{i=1}^I\hat{Y}_{i}\)</span>. estes valores podem também ser utilizados para a construção do gráfico de regressão ajustada.</p>
<p>No nosso exemplo, temos:</p>
<table>
<thead>
<tr class="header">
<th align="left">Dose de Gesso (X)</th>
<th align="center"><span class="math inline">\(\bar{Y}_{i~Obs}\)</span></th>
<th align="center"><span class="math inline">\(\hat{Y}_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="center">138.60</td>
<td align="center">140.78</td>
</tr>
<tr class="even">
<td align="left">50</td>
<td align="center">153.60</td>
<td align="center">152.51</td>
</tr>
<tr class="odd">
<td align="left">100</td>
<td align="center">164.53</td>
<td align="center">160.32</td>
</tr>
<tr class="even">
<td align="left">150</td>
<td align="center">164.93</td>
<td align="center">164.22</td>
</tr>
<tr class="odd">
<td align="left">200</td>
<td align="center">158.73</td>
<td align="center">164.20</td>
</tr>
<tr class="even">
<td align="left">250</td>
<td align="center">159.98</td>
<td align="center">160.27</td>
</tr>
<tr class="odd">
<td align="left">300</td>
<td align="center">154.43</td>
<td align="center">152.42</td>
</tr>
<tr class="even">
<td align="left"><strong>Total</strong></td>
<td align="center"><strong>1094.80</strong></td>
<td align="center"><strong>1094.72</strong></td>
</tr>
</tbody>
</table>
<p><img src="R.png" /></p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb198-1"></a><span class="kw">require</span>(ExpDes.pt)</span>
<span id="cb198-2"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb198-2"></a>caminho&lt;-<span class="st">&quot;https://raw.githubusercontent.com/arpanosso/ExpAgr_2020/master/dados/feijaoREG.txt&quot;</span></span>
<span id="cb198-3"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb198-3"></a>d&lt;-<span class="kw">read.table</span>(caminho,<span class="dt">h=</span>T)</span>
<span id="cb198-4"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb198-4"></a><span class="co"># Análise de Variância</span></span>
<span id="cb198-5"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb198-5"></a><span class="kw">dic</span>(d<span class="op">$</span>trat,d<span class="op">$</span>y,<span class="dt">quali =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## ------------------------------------------------------------------------
## Quadro da analise de variancia
## ------------------------------------------------------------------------
##            GL      SQ QM    Fc      Pr&gt;Fc
## Tratamento  6 1941.83  2 7.668 0.00018763
## Residuo    21  886.34  3                 
## Total      27 2828.17  1                 
## ------------------------------------------------------------------------
## CV = 4.15 %
## 
## ------------------------------------------------------------------------
## Teste de normalidade dos residuos 
## Valor-p:  0.5471519 
## De acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.
## ------------------------------------------------------------------------
## 
## ------------------------------------------------------------------------
## Teste de homogeneidade de variancia 
## valor-p:  0.3337639 
## De acordo com o teste de bartlett a 5% de significancia, as variancias podem ser consideradas homogeneas.
## ------------------------------------------------------------------------
## 
## Ajuste de modelos polinomiais de regressao
## ------------------------------------------------------------------------
## 
## Modelo Linear
## =========================================
##    Estimativa Erro.padrao   tc    valor.p
## -----------------------------------------
## b0  150.5652    2.2134    68.0255    0   
## b1   0.0389     0.0123    3.1664  0.0046 
## -----------------------------------------
## 
## R2 do modelo linear
## --------
## 0.217915
## --------
## 
## Analise de variancia do modelo linear
## =========================================================
##                      GL     SQ        QM     Fc   valor.p
## ---------------------------------------------------------
## Efeito linear        1   423.1544  423.1544 10.03 0.00465
## Desvios de Regressao 5  1,518.6780 303.7356  7.2  0.00046
## Residuos             21  886.3375  42.2066               
## ---------------------------------------------------------
## ------------------------------------------------------------------------
## 
## Modelo quadratico
## =========================================
##    Estimativa Erro.padrao   tc    valor.p
## -----------------------------------------
## b0  140.7839    2.8354    49.6527    0   
## b1   0.2736     0.0443    6.1812     0   
## b2  -0.0008     0.0001    -5.5196 0.00002
## -----------------------------------------
## 
## R2 do modelo quadratico
## --------
## 0.880095
## --------
## 
## Analise de variancia do modelo quadratico
## ===========================================================
##                      GL     SQ         QM      Fc   valor.p
## -----------------------------------------------------------
## Efeito linear        1   423.1544   423.1544  10.03 0.00465
## Efeito quadratico    1  1,285.8430 1,285.8430 30.47  2e-05 
## Desvios de Regressao 4   232.8346   58.2087   1.38  0.27505
## Residuos             21  886.3375   42.2066                
## -----------------------------------------------------------
## ------------------------------------------------------------------------
## 
## Modelo cubico
## =========================================
##    Estimativa Erro.padrao   tc    valor.p
## -----------------------------------------
## b0  138.2423    3.1302    44.1645    0   
## b1   0.4431     0.0989    4.4812  0.0002 
## b2  -0.0023     0.0008    -2.8551 0.0095 
## b3  0.000003       0      1.9166  0.0690 
## -----------------------------------------
## 
## R2 do modelo cubico
## --------
## 0.959938
## --------
## 
## Analise de variancia do modelo cubico
## ===========================================================
##                      GL     SQ         QM      Fc   valor.p
## -----------------------------------------------------------
## Efeito linear        1   423.1544   423.1544  10.03 0.00465
## Efeito quadratico    1  1,285.8430 1,285.8430 30.47  2e-05 
## Efeito cubico        1   155.0417   155.0417  3.67   0.069 
## Desvios de Regressao 3   77.7930    25.9310   0.61  0.61327
## Residuos             21  886.3375   42.2066                
## -----------------------------------------------------------
## ------------------------------------------------------------------------</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-1"></a><span class="co"># Construção do gráfico</span></span>
<span id="cb200-2"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-2"></a>X&lt;-<span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">300</span>,<span class="dv">50</span>)</span>
<span id="cb200-3"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-3"></a>Y&lt;-<span class="kw">tapply</span>(d<span class="op">$</span>y, d<span class="op">$</span>trat, mean)</span>
<span id="cb200-4"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-4"></a><span class="kw">plot</span>(Y<span class="op">~</span>X,</span>
<span id="cb200-5"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-5"></a>     <span class="dt">las=</span><span class="dv">1</span>,</span>
<span id="cb200-6"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-6"></a>     <span class="dt">pch=</span><span class="dv">21</span>,<span class="dt">col=</span><span class="st">&quot;black&quot;</span>,<span class="dt">bg=</span><span class="st">&quot;gray&quot;</span>,<span class="dt">cex=</span><span class="fl">1.3</span>,</span>
<span id="cb200-7"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-7"></a>     <span class="dt">xlab=</span><span class="st">&quot;Dose de Gesso (kg/ha)&quot;</span>,</span>
<span id="cb200-8"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-8"></a>     <span class="dt">ylab=</span><span class="st">&quot;Peso de 1000 sementes (g)&quot;</span></span>
<span id="cb200-9"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-9"></a>);<span class="kw">curve</span>(<span class="fl">140.7836+0.2737</span><span class="op">*</span>x<span class="fl">-0.000783</span><span class="op">*</span>x<span class="op">^</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</span>
<span id="cb200-10"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cb200-10"></a><span class="kw">text</span>(<span class="dv">155</span>,<span class="dv">145</span>,<span class="st">&quot;140.7836+0.2737X-0.000783X²\nR²=0.8801&quot;</span>)</span></code></pre></div>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p>Gráfico 1. relação entre o Peso de 1000 sementes e a dose de gesso aplicada.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="experimentos-em-parcelas-subdivididas.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["curso_GIEU.pdf", "curso_GIEU.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
