<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES | Curso do R do GIEU</title>
  <meta name="description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES | Curso do R do GIEU" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES | Curso do R do GIEU" />
  
  <meta name="twitter:description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  

<meta name="author" content="José C. Barbosa &amp; Alan R. Panosso" />


<meta name="date" content="2020-10-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="planejamento-de-experimentos.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">curso_GIEU</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUÇÃO AO CURSO</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#alguns-conceitos-básicos"><i class="fa fa-check"></i><b>1.1</b> Alguns conceitos básicos</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#medidas-de-posição-e-de-tendência-central"><i class="fa fa-check"></i><b>1.2</b> Medidas de posição e de tendência central</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html"><i class="fa fa-check"></i><b>2</b> COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES</a><ul>
<li class="chapter" data-level="2.1" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html#comparação-da-variância-de-duas-populações-normais"><i class="fa fa-check"></i><b>2.1</b> Comparação da variância de duas populações normais</a></li>
<li class="chapter" data-level="2.2" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html#comparação-de-duas-médias-de-populações-normais-amostras-independentes"><i class="fa fa-check"></i><b>2.2</b> Comparação de duas médias de populações normais: amostras independentes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html"><i class="fa fa-check"></i><b>3</b> PLANEJAMENTO DE EXPERIMENTOS</a><ul>
<li class="chapter" data-level="3.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>3.1</b> Introdução</a></li>
<li class="chapter" data-level="3.2" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#unidade-experimental-ou-parcela"><i class="fa fa-check"></i><b>3.2</b> Unidade Experimental ou Parcela</a></li>
<li class="chapter" data-level="3.3" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#princípios-básicos-da-experimentação"><i class="fa fa-check"></i><b>3.3</b> Princípios Básicos da Experimentação</a></li>
<li class="chapter" data-level="3.4" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#relação-entre-os-princípios-básico-da-experimentação-e-os-delineamentos-experimentais"><i class="fa fa-check"></i><b>3.4</b> Relação entre os princípios básico da experimentação e os delineamentos experimentais</a></li>
<li class="chapter" data-level="3.5" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#testes-de-significância"><i class="fa fa-check"></i><b>3.5</b> Testes de Significância</a></li>
<li class="chapter" data-level="3.6" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#teste-f-de-snedecor-para-análise-de-variância"><i class="fa fa-check"></i><b>3.6</b> Teste F de Snedecor para Análise de Variância</a></li>
<li class="chapter" data-level="3.7" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#exemplo-de-aplicação-do-teste-f"><i class="fa fa-check"></i><b>3.7</b> Exemplo de aplicação do teste F</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html"><i class="fa fa-check"></i><b>4</b> TESTES PARA COMPARAÇÃO DE MÉDIAS</a><ul>
<li class="chapter" data-level="4.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>4.1</b> Introdução</a></li>
<li class="chapter" data-level="4.2" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#contrastes-de-médias"><i class="fa fa-check"></i><b>4.2</b> Contrastes de Médias</a></li>
<li class="chapter" data-level="4.3" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#estimativa-do-contrastes"><i class="fa fa-check"></i><b>4.3</b> Estimativa do Contrastes</a></li>
<li class="chapter" data-level="4.4" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#covariância-entre-dois-contrastes"><i class="fa fa-check"></i><b>4.4</b> Covariância entre dois contrastes</a></li>
<li class="chapter" data-level="4.5" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>4.5</b> Contrastes ortogonais</a></li>
<li class="chapter" data-level="4.6" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#variância-de-um-contraste"><i class="fa fa-check"></i><b>4.6</b> Variância de um contraste</a></li>
<li class="chapter" data-level="4.7" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#erro-padrão-do-contraste"><i class="fa fa-check"></i><b>4.7</b> Erro padrão do contraste</a></li>
<li class="chapter" data-level="4.8" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-t-de-student"><i class="fa fa-check"></i><b>4.8</b> Teste t de Student</a></li>
<li class="chapter" data-level="4.9" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-t-de-student"><i class="fa fa-check"></i><b>4.9</b> Exemplo de aplicação do teste t de Student</a></li>
<li class="chapter" data-level="4.10" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-tukey"><i class="fa fa-check"></i><b>4.10</b> Teste de Tukey</a></li>
<li class="chapter" data-level="4.11" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-tukey"><i class="fa fa-check"></i><b>4.11</b> Exemplo de aplicação do teste de Tukey</a></li>
<li class="chapter" data-level="4.12" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-duncan"><i class="fa fa-check"></i><b>4.12</b> Teste de Duncan</a></li>
<li class="chapter" data-level="4.13" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-duncan"><i class="fa fa-check"></i><b>4.13</b> Exemplo de aplicação do teste de Duncan</a></li>
<li class="chapter" data-level="4.14" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-scheffé"><i class="fa fa-check"></i><b>4.14</b> Teste de Scheffé</a></li>
<li class="chapter" data-level="4.15" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-scheffé"><i class="fa fa-check"></i><b>4.15</b> Exemplo de aplicação do teste de Scheffé</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html"><i class="fa fa-check"></i><b>5</b> DELINEAMENTO INTEIRAMENTE CASUALIZADO</a><ul>
<li class="chapter" data-level="5.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#caracterização"><i class="fa fa-check"></i><b>5.1</b> Caracterização</a></li>
<li class="chapter" data-level="5.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático"><i class="fa fa-check"></i><b>5.2</b> Modelo Matemático</a></li>
<li class="chapter" data-level="5.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#hipóteses-básicas-para-aplicação-da-análoise-de-variância"><i class="fa fa-check"></i><b>5.3</b> Hipóteses básicas para aplicação da análoise de variância</a></li>
<li class="chapter" data-level="5.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>5.4</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="5.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>5.5</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><i class="fa fa-check"></i><b>6</b> DELINEAMENTO INTEIRAMENTE CASUALIZADO COM NÚMERO DIFERENTE DE REPETIÇÕES POR TRATAMENTO</a><ul>
<li class="chapter" data-level="6.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>6.1</b> Introdução</a></li>
<li class="chapter" data-level="6.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>6.2</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="6.3" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-das-médias-e-error-padrôes-das-médias"><i class="fa fa-check"></i><b>6.3</b> Cálculo das médias e error padrôes das médias</a></li>
<li class="chapter" data-level="6.4" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#teste-de-tukey-para-comparação-das-médias"><i class="fa fa-check"></i><b>6.4</b> Teste de Tukey para comparação das médias</a></li>
<li class="chapter" data-level="6.5" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>6.5</b> Cálculo do coeficiente de variação do experimento</a></li>
<li class="chapter" data-level="6.6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#aplicação-do-teste-t-de-student-a-um-contraste"><i class="fa fa-check"></i><b>6.6</b> Aplicação do teste t de Student a um contraste</a></li>
<li class="chapter" data-level="6.7" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#teste-de-duncan-para-a-comparação-das-médias"><i class="fa fa-check"></i><b>6.7</b> Teste de Duncan para a comparação das médias</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><i class="fa fa-check"></i><b>7</b> DESDOBRAMENTO DE GRAUS DE LIBERDADE DE TRATAMENTOS</a><ul>
<li class="chapter" data-level="7.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>7.1</b> Introdução</a></li>
<li class="chapter" data-level="7.2" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#obtenção-da-análise-de-variância-com-desdobramento-dos-graus-de-liberdade-de-tratamentos"><i class="fa fa-check"></i><b>7.2</b> Obtenção da análise de variância com desdobramento dos graus de liberdade de tratamentos</a></li>
<li class="chapter" data-level="7.3" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#método-dos-contrastes-de-totais-de-tratamentos"><i class="fa fa-check"></i><b>7.3</b> Método dos contrastes de totais de tratamentos</a></li>
<li class="chapter" data-level="7.4" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#método-dos-totais-de-tratamentos-sem-utilizar-contrastes"><i class="fa fa-check"></i><b>7.4</b> Método dos totais de tratamentos (sem utilizar contrastes)</a></li>
<li class="chapter" data-level="7.5" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#análise-de-variância-com-desdobramento-dos-graus-de-liberdade-de-tratamentos"><i class="fa fa-check"></i><b>7.5</b> Análise de variância com desdobramento dos graus de liberdade de tratamentos</a><ul>
<li class="chapter" data-level="7.5.1" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#conclusões"><i class="fa fa-check"></i><b>7.5.1</b> <strong>Conclusões</strong></a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#componentes-com-maisde-um-grau-de-liberdade"><i class="fa fa-check"></i><b>7.6</b> Componentes com maisde um grau de liberdade</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="delineamento-em-blocos-casualizados.html"><a href="delineamento-em-blocos-casualizados.html"><i class="fa fa-check"></i><b>8</b> DELINEAMENTO EM BLOCOS CASUALIZADOS</a><ul>
<li class="chapter" data-level="8.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#caracterização"><i class="fa fa-check"></i><b>8.1</b> Caracterização</a></li>
<li class="chapter" data-level="8.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático"><i class="fa fa-check"></i><b>8.2</b> Modelo matemático</a></li>
<li class="chapter" data-level="8.3" data-path="delineamento-em-blocos-casualizados.html"><a href="delineamento-em-blocos-casualizados.html#hipóteses-básicas"><i class="fa fa-check"></i><b>8.3</b> Hipóteses básicas</a></li>
<li class="chapter" data-level="8.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>8.4</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="8.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>8.5</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><i class="fa fa-check"></i><b>9</b> DELINEAMENTO EM BLOCOS CASUALIZADOS COM UMA PARCELA PERDIDA</a><ul>
<li class="chapter" data-level="9.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>9.1</b> Introdução</a></li>
<li class="chapter" data-level="9.2" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#estimativa-da-parcela-perdida"><i class="fa fa-check"></i><b>9.2</b> Estimativa da parcela perdida</a></li>
<li class="chapter" data-level="9.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>9.3</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="9.4" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#médias-de-tratamentos"><i class="fa fa-check"></i><b>9.4</b> Médias de tratamentos</a></li>
<li class="chapter" data-level="9.5" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#erros-padrões-das-médias"><i class="fa fa-check"></i><b>9.5</b> Erros padrões das médias</a></li>
<li class="chapter" data-level="9.6" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#comparação-de-médias-pelo-teste-de-tukey"><i class="fa fa-check"></i><b>9.6</b> Comparação de médias pelo teste de Tukey</a></li>
<li class="chapter" data-level="9.7" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>9.7</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html"><i class="fa fa-check"></i><b>10</b> EXPERIMENTOS FATORIAIS</a><ul>
<li class="chapter" data-level="10.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>10.1</b> Introdução</a></li>
<li class="chapter" data-level="10.2" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-simples-de-um-fator"><i class="fa fa-check"></i><b>10.2</b> Efeito simples de um fator</a></li>
<li class="chapter" data-level="10.3" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-principal-de-um-fator"><i class="fa fa-check"></i><b>10.3</b> Efeito principal de um fator</a></li>
<li class="chapter" data-level="10.4" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-da-interação-entre-fatores"><i class="fa fa-check"></i><b>10.4</b> Efeito da interação entre fatores</a></li>
<li class="chapter" data-level="10.5" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#vantagens-dos-experimentos-fatoriais"><i class="fa fa-check"></i><b>10.5</b> Vantagens dos experimentos fatoriais</a></li>
<li class="chapter" data-level="10.6" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#desvantagens-dos-experimentos-fatoriais"><i class="fa fa-check"></i><b>10.6</b> Desvantagens dos experimentos fatoriais</a></li>
<li class="chapter" data-level="10.7" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#classificação-dos-experementos-fatoriais"><i class="fa fa-check"></i><b>10.7</b> Classificação dos Experementos Fatoriais</a></li>
<li class="chapter" data-level="10.8" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#casualização-dos-tratamentos"><i class="fa fa-check"></i><b>10.8</b> Casualização dos tratamentos</a></li>
<li class="chapter" data-level="10.9" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#análise-de-variância-de-um-experimento-fatorial-com-2-fatores-com-interação-não-significativa"><i class="fa fa-check"></i><b>10.9</b> Análise de variância de um experimento fatorial com 2 fatores com interação não significativa</a></li>
<li class="chapter" data-level="10.10" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>10.10</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="10.11" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#cálculo-das-média-de-tratamento-do-solo-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>10.11</b> Cálculo das média de Tratamento do Solo e erros padrões das médias</a></li>
<li class="chapter" data-level="10.12" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#cálculo-das-média-de-fungicidas-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>10.12</b> Cálculo das média de Fungicidas e erros padrões das médias</a></li>
<li class="chapter" data-level="10.13" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>10.13</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><i class="fa fa-check"></i><b>11</b> ANÁLISE DE UM EXPERIMENTO FATORIAL COM 2 FATORES, COM INTERAÇÃO SIGNIFICATIVA</a><ul>
<li class="chapter" data-level="11.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>11.1</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="11.2" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#desdobrando-a-interação-itimes-d-para-estudar-os-efeitos-do-fator-doses-em-cada-nível-do-fator-inseticida-d-d.-i"><i class="fa fa-check"></i><b>11.2</b> Desdobrando a interação <span class="math inline">\(I\times D\)</span>, para estudar os efeitos do fator <strong>DOSES</strong> em cada nível do fator <strong>INSETICIDA</strong> (D d. I):</a></li>
<li class="chapter" data-level="11.3" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#desdobrando-a-interação-i-times-d-para-estudar-os-efeitos-do-fator-inseticidas-dentro-de-cada-nível-do-fator-dose-d-d.-i"><i class="fa fa-check"></i><b>11.3</b> Desdobrando a interação <span class="math inline">\(I \times D\)</span>, para estudar os efeitos do fator <strong>INSETICIDAS</strong> dentro de cada nível do fator <strong>DOSE</strong> (D d. I):</a></li>
<li class="chapter" data-level="11.4" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#teste-de-tukey-para-a-comparação-de-médias"><i class="fa fa-check"></i><b>11.4</b> Teste de Tukey para a comparação de médias</a></li>
<li class="chapter" data-level="11.5" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#para-comparar-médias-de-inseticidas-na-dose-1-i-d.-d_1"><i class="fa fa-check"></i><b>11.5</b> Para comparar médias de Inseticidas na Dose 1 (I d. <span class="math inline">\(D_1\)</span>)</a></li>
<li class="chapter" data-level="11.6" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#para-comparar-médias-de-inseticidas-na-dose-2-i-d.-d_2"><i class="fa fa-check"></i><b>11.6</b> Para comparar médias de Inseticidas na Dose 2 (I d. <span class="math inline">\(D_2\)</span>)</a></li>
<li class="chapter" data-level="11.7" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>11.7</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html"><i class="fa fa-check"></i><b>12</b> Estudo do Fatorial <span class="math inline">\(3^2\)</span></a><ul>
<li class="chapter" data-level="12.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>12.1</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="12.2" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#desdobrando-a-interação-etimes-d-para-estudar-os-efeitos-do-fator-espaçamento-em-cada-nível-do-fator-densidade-e-d.-d"><i class="fa fa-check"></i><b>12.2</b> Desdobrando a interação <span class="math inline">\(E\times D\)</span>, para estudar os efeitos do fator <strong>Espaçamento</strong> em cada nível do fator <strong>Densidade</strong> (E d. D):</a></li>
<li class="chapter" data-level="12.3" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#desdobrando-a-interação-etimes-d-para-estudar-os-efeitos-do-fator-densidade-em-cada-nível-do-fator-espaçamentos-d-d.-e"><i class="fa fa-check"></i><b>12.3</b> Desdobrando a interação <span class="math inline">\(E\times D\)</span>, para estudar os efeitos do fator <strong>Densidade</strong> em cada nível do fator <strong>Espaçamentos</strong> (D d. E):</a></li>
<li class="chapter" data-level="12.4" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#teste-de-tukey-para-a-comparação-de-médias"><i class="fa fa-check"></i><b>12.4</b> Teste de Tukey para a comparação de médias</a></li>
<li class="chapter" data-level="12.5" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#resultado-do-teste-de-tukey"><i class="fa fa-check"></i><b>12.5</b> Resultado do teste de Tukey</a></li>
<li class="chapter" data-level="12.6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>12.6</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html"><i class="fa fa-check"></i><b>13</b> Estudo do Fatorial <span class="math inline">\(2^3\)</span></a><ul>
<li class="chapter" data-level="13.1" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#análise-de-variância-de-um-experimento-fatorial-23"><i class="fa fa-check"></i><b>13.1</b> Análise de variância de um experimento fatorial <span class="math inline">\(2^3\)</span></a></li>
<li class="chapter" data-level="13.2" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-das-somas-de-quadrados-pelo-método-dos-contrastes-de-totais-de-tratamentos."><i class="fa fa-check"></i><b>13.2</b> Cálculo das somas de quadrados pelo método dos contrastes de totais de tratamentos.</a></li>
<li class="chapter" data-level="13.3" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#desdobramento-da-interação-n-times-k"><i class="fa fa-check"></i><b>13.3</b> Desdobramento da Interação <span class="math inline">\(N \times K\)</span></a></li>
<li class="chapter" data-level="13.4" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-das-médias-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>13.4</b> Cálculo das médias e erros padrões das médias</a></li>
<li class="chapter" data-level="13.5" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-do-coeficiente-de-variação"><i class="fa fa-check"></i><b>13.5</b> Cálculo do coeficiente de variação</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html"><i class="fa fa-check"></i><b>14</b> Experimentos em Parcelas Subdivididas</a><ul>
<li class="chapter" data-level="14.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>14.1</b> Introdução</a></li>
<li class="chapter" data-level="14.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>14.2</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="14.3" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#desdobramento-da-interação-e-times-v-para-estudar-os-efeitos-de-variedades-dentro-de-cada-época-de-plantio-v-d.-e"><i class="fa fa-check"></i><b>14.3</b> 1. Desdobramento da interação E <span class="math inline">\(\times\)</span> V para estudar os efeitos de Variedades dentro de cada Época de plantio (V d. E):</a></li>
<li class="chapter" data-level="14.4" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#desdobramento-da-interação-e-times-v-para-estudar-os-efeitos-de-épocas-dentro-de-cada-variedade-e-d.-v"><i class="fa fa-check"></i><b>14.4</b> 2. Desdobramento da interação E <span class="math inline">\(\times\)</span> V para estudar os efeitos de Épocas dentro de cada Variedade (E d. V):</a></li>
<li class="chapter" data-level="14.5" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-das-médias"><i class="fa fa-check"></i><b>14.5</b> Cálculo das médias</a></li>
<li class="chapter" data-level="14.6" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-dos-erros-padrões"><i class="fa fa-check"></i><b>14.6</b> Cálculo dos erros padrões:</a></li>
<li class="chapter" data-level="14.7" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-dos-coeficientes-de-variação-do-experimento"><i class="fa fa-check"></i><b>14.7</b> Cálculo dos coeficientes de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html"><i class="fa fa-check"></i><b>15</b> Análise de Regressão por Polinômios Ortogonais</a><ul>
<li class="chapter" data-level="15.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>15.1</b> Introdução</a></li>
<li class="chapter" data-level="15.2" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#obtenção-da-análise-de-variância-estudando-se-os-efeitos-da-regressão"><i class="fa fa-check"></i><b>15.2</b> Obtenção da análise de variância, estudando-se os efeitos da regressão</a></li>
<li class="chapter" data-level="15.3" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#coeficientes-de-interpolação-de-polinômios-ortogonais"><i class="fa fa-check"></i><b>15.3</b> Coeficientes de interpolação de polinômios ortogonais</a></li>
<li class="chapter" data-level="15.4" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#obtendo-a-equação-de-regressão"><i class="fa fa-check"></i><b>15.4</b> Obtendo a Equação de Regressão</a></li>
<li class="chapter" data-level="15.5" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cálculo-do-coeficiente-de-determinação-r²"><i class="fa fa-check"></i><b>15.5</b> Cálculo do Coeficiente de Determinação (R²)</a></li>
<li class="chapter" data-level="15.6" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#gráfico-da-regressão-ajustada"><i class="fa fa-check"></i><b>15.6</b> Gráfico da Regressão Ajustada</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso do R do GIEU</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparações-de-parâmetros-de-duas-populações" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES</h1>
<div id="comparação-da-variância-de-duas-populações-normais" class="section level2">
<h2><span class="header-section-number">2.1</span> Comparação da variância de duas populações normais</h2>
<p>Suponha duas amostras aleatórias independentes de tamanhos <span class="math inline">\(n_1\)</span> e <span class="math inline">\(n_2\)</span> ou seja, <span class="math inline">\(X_1,X_2,...,X_{n_1}\)</span> e <span class="math inline">\(Y_1,Y_2,...,Y_{n_2}\)</span>, respectivamente, de uma população com distribuição <span class="math inline">\(N(\mu_1, \sigma_1^2)\)</span> e de uma população com distribuição <span class="math inline">\(N(\mu_2, \sigma_2^2)\)</span>.</p>
<p><strong>Hipóteses:</strong>
<span class="math display">\[
H_0: \sigma_1^2 = \sigma_2^2 \text{   ou   } (\sigma_1^2 /\sigma_2^2 =1) \\
H_1: \sigma_1^2 \neq \sigma_2^2 \text{   ou   } (\sigma_1^2 /\sigma_2^2 \neq 1)
\]</span></p>
<p><strong>Estatística do Teste</strong></p>
<p>Sendo <span class="math inline">\(s_1^2\)</span> e <span class="math inline">\(s_2^2\)</span> as variâncias, respectivamente, das amostras <span class="math inline">\(n_1\)</span> e <span class="math inline">\(n_2\)</span>, o quociente</p>
<p><span class="math display">\[
 \frac{s^2_1/\sigma^2_1}{s^2_2/\sigma^2_2}
\]</span>
Segue uma distribuição <strong>F de Snedecor</strong> com <span class="math inline">\(n_1-1\)</span> e <span class="math inline">\(n_2-1\)</span> graus de liberdade (GL), denotada por <span class="math inline">\(F(n_1-1,n_2-1)\)</span></p>
<p>Sob a suposição de <span class="math inline">\(H_0\)</span> ser verdadeira, isto é, <span class="math inline">\(\sigma_1^2 = \sigma_2^2\)</span>, tem-se que</p>
<p><span class="math display">\[
F= \frac{s^2_1}{s^2_2}: F(n_1-1,n_2-1)
\]</span>
A distribuição F é relacionada à distribuição <span class="math inline">\(\chi^2\)</span> (lê-se Qui-quadrado).</p>
<p>Para maiores informações: <img src="YT.png" /> <a href="https://www.youtube.com/watch?v=G_RDxAZJ-ug">An Introduction to the F Distribution</a></p>
<p>A função densidade probabilidade da distribuição F é dada por:</p>
<p><span class="math display">\[
f(x) = \frac{\Gamma(\frac{\nu1+\nu2}{2})(\frac{\nu1}{\nu2})^{\frac{\nu1}{2}}x^{\frac{\nu1}{2}-1}}{\Gamma(\frac{\nu1}{2}) \Gamma(\frac{\nu2}{2}) (1+\frac{\nu1}{\nu2}x)^{\frac{\nu1+\nu2}{2}}} \text{   para   } x&gt; 0 
\]</span>
Onde: <span class="math inline">\(\nu1\)</span> são os graus de liberdade de <span class="math inline">\(s^2_1\)</span>, <span class="math inline">\(\nu2\)</span> são os graus de liberdade de <span class="math inline">\(s^2_2\)</span> e <span class="math inline">\(\Gamma\)</span> é a função gama, uma extensão da função fatorial para números reais positivos.</p>
<p><strong>Construção da região crítica:</strong></p>
<p>Fixado <span class="math inline">\(\alpha\)</span>, os pontos críticos serão <em>F1</em> e <em>F2</em> da distribuição F, tais que:</p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Se <span class="math inline">\(\alpha = 10\%\)</span>, pode-se, utilizando a Tabela abaixo, encontrar diretamente <span class="math inline">\(F_{2(5\%)}\)</span>:</p>
<p><img src="tabF.png" /></p>
<p><a href="https://github.com/arpanosso/ExpAgr_2020/raw/master/TabelaF.pdf">Download da Tabela</a></p>
<p><strong>exemplo</strong></p>
<p>Dado: <span class="math inline">\(n_1-1\)</span> = 5 e <span class="math inline">\(n_2-1\)</span> = 7, a um <span class="math inline">\(\alpha\)</span> de 5% (alpha da tabela) temos que olhar na coluna 5 (graus de liberdade do numerador) e na linha 7 (graus de liberdade do denominador) e teremos o valor <span class="math inline">\(F_2 = 3,97\)</span></p>
<p>Para encontrarmos <span class="math inline">\(F_{1(5\%)}\)</span>, utilizamos uma propriedade de integração, o que na prática significa:</p>
<p><span class="math display">\[
F_{(1-\alpha, n_1-1, n_2-1)} = \frac{1}{F_{(\alpha, n_2-1, n_1-1)}} \\
\text{ou seja} \\
F_{(95\%, n_1-1, n_2-1)} = \frac{1}{F_{(5\%, n_2-1, n_1-1)}} \\
F_{(95\%, 5, 7)} = \frac{1}{F_{(5\%, 7, 5)}} = \frac{1}{4,88} = 0,205
\]</span></p>
<p>O valor é o inverso daquele observado na Tabela, obtido pela inversão dos graus de liberdade.</p>
<p>Portanto, a região crítica do teste será: <span class="math inline">\(RC = \{ F &lt; 0,205 \text{  ou  } F &gt; 3,97 \}\)</span>.</p>
<p>O mesmo valor pode ser obtido no R a partir da função <code>qf(p,df1,df2)</code>, cujos argumentos são: <code>p</code> o valor da área (probabilidade) acumulada até o valor F desejado, <code>df1</code> é o grau de liberdade do numerador e <code>df2</code> é o grau de liberdade do denominador:</p>
<p><img src="R.png" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="comparações-de-parâmetros-de-duas-populações.html#cb19-1"></a><span class="kw">qf</span>(<span class="fl">0.95</span>,<span class="dv">5</span>,<span class="dv">7</span>) <span class="co"># F2</span></span></code></pre></div>
<pre><code>## [1] 3.971523</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="comparações-de-parâmetros-de-duas-populações.html#cb21-1"></a><span class="kw">qf</span>(<span class="fl">0.05</span>,<span class="dv">5</span>,<span class="dv">7</span>) <span class="co"># F1</span></span></code></pre></div>
<pre><code>## [1] 0.2050915</code></pre>
<p>Na prática o procedimento é mais simples: primeiro calcula-se o <span class="math inline">\(F\)</span> da amostra utilizando sempre o maior valor de variância no numerador <span class="math inline">\((s^2_1 &gt; s_2^2)\)</span>, portanto <span class="math inline">\(F &gt; 1\)</span> e consideramos o ponto crítico sempre em <span class="math inline">\(F_{2(\alpha, n_1-1, n_2-1)}\)</span></p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Assim, a <strong>região crítica</strong> do teste será <span class="math inline">\(RC = \{F &gt; F_c\}\)</span></p>
<p>Calculamos a <strong>estatística na amostra</strong> como :</p>
<p><span class="math display">\[
F_{obs} = \frac{s^2_1}{s^2_2} \text{, com }  s_1^2 &gt; s^2_2
\]</span>
As <strong>hipóteses</strong> sempre serão
<span class="math display">\[
H_0: \sigma_1^2 = \sigma_2^2 \text{   ou   } (\sigma_1^2 /\sigma_2^2 =1) \\
H_1: \sigma_1^2 &gt; \sigma_2^2 \text{   ou   } (\sigma_1^2 /\sigma_2^2 &gt; 1)
\]</span></p>
<p><strong>Conclusão</strong></p>
<p>Se <span class="math inline">\(F_{obs} \not\in RC\)</span> então <strong>não rejeitamos</strong> <span class="math inline">\(H_0\)</span> e concluímos que as variâncias são iguais ou seja <strong>HOMOCEDÁSTICAS</strong></p>
<p>Se <span class="math inline">\(F_{obs} \in RC\)</span> então <strong>rejeitamos</strong> <span class="math inline">\(H_0\)</span> e concluímos que as variâncias são diferentes ou seja <strong>HETEROCEDÁSTICAS</strong></p>
<p><strong>EXEMPLO</strong>:</p>
<p>Em um ensaio de competição de 2 cultivares de milho, onde a cultivar <span class="math inline">\(A\)</span> foi plantada e 6 parcelas (n=6 amostras) e a cultivar B em 8 parcelas amostras (n=8 amostras), as produções em kg/ha foram obervadas na tabela:</p>
<table>
<thead>
<tr class="header">
<th>Cultivar</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1470</td>
<td>1920</td>
<td>2340</td>
<td>2100</td>
<td>1920</td>
<td>1480</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>3260</td>
<td>3990</td>
<td>4050</td>
<td>3420</td>
<td>3510</td>
<td>3880</td>
<td>3550</td>
<td>3660</td>
<td></td>
</tr>
</tbody>
</table>
<p>Comparar ao nível de 5% de significância se as variâncias desses cultivares são iguais</p>
<p><strong>PASSO 1:</strong> Definir <span class="math inline">\(H_0\)</span> e <span class="math inline">\(H_1\)</span>.
<span class="math display">\[
H_0: \sigma_1^2 = \sigma_2^2 \text{   ou   } (\sigma_1^2 /\sigma_2^2 =1) \\
H_1: \sigma_1^2 &gt; \sigma_2^2 \text{   ou   } (\sigma_1^2 /\sigma_2^2 &gt; 1)
\]</span></p>
<p><strong>PASSO 2:</strong> Calcular a estatística do teste.</p>
<p>Definir os graus de liberdade:</p>
<p><span class="math display">\[
n_A = 6 \\
n_B = 8
\]</span></p>
<p>Assim:</p>
<p><span class="math display">\[
\nu_1 = 6 - 1 = 5 \\
\nu_2 = 8 - 1 = 7 \\
\]</span></p>
<p>Calcular as variâncias de A e B</p>
<p><span class="math display">\[
s_A^2 = 118176,7 \\
s_B^2 = 80200,00 
\]</span></p>
<p>Como <span class="math inline">\(s^2_A &gt; s^2_B\)</span> vamos calcular o <span class="math inline">\(F_{obs}\)</span></p>
<p><span class="math display">\[
F_{obs} = \frac{s^2_A}{s^2_B} = \frac{118076,7}{80200}=1,4735
\]</span>
<strong>PASSO 3:</strong> Construir a Região Crítica.</p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Olhando na tabela <span class="math inline">\(F_{(0,05; 5; 7)} = 3,97\)</span></p>
<p>Assim, a <strong>região crítica</strong> do teste será <span class="math inline">\(RC = \{F &gt; 3,97\}\)</span></p>
<p><strong>PASSO 4:</strong> Comparar <span class="math inline">\(F_{obs}\)</span> com o <span class="math inline">\(F_c\)</span>.</p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p><strong>PASSO 5:</strong> Concluir o teste.</p>
<p>Como <span class="math inline">\(F{obs} \not\in RC\)</span> <strong>não rejeitamos </strong> <span class="math inline">\(H_0\)</span> ao nível de 5% de significância, e concluímos que as variedades de milhos testadas têm variâncias semelhantes, ou seja, são <strong>homocedásticas</strong>.</p>
<p><strong>Resolvendo no R</strong></p>
<p><img src="Rlogo.png" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="comparações-de-parâmetros-de-duas-populações.html#cb23-1"></a><span class="co"># Construir os vetores de dados</span></span>
<span id="cb23-2"><a href="comparações-de-parâmetros-de-duas-populações.html#cb23-2"></a>vA&lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1470</span>,<span class="dv">1920</span>,<span class="dv">2340</span>,<span class="dv">2100</span>,<span class="dv">1920</span>,<span class="dv">1480</span>)</span>
<span id="cb23-3"><a href="comparações-de-parâmetros-de-duas-populações.html#cb23-3"></a>vB&lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3260</span>,<span class="dv">3990</span>,<span class="dv">4050</span>,<span class="dv">3420</span>,<span class="dv">3510</span>,<span class="dv">3880</span>,<span class="dv">3550</span>,<span class="dv">3660</span>)</span>
<span id="cb23-4"><a href="comparações-de-parâmetros-de-duas-populações.html#cb23-4"></a></span>
<span id="cb23-5"><a href="comparações-de-parâmetros-de-duas-populações.html#cb23-5"></a><span class="co"># Aplicar o teste de variâncias</span></span>
<span id="cb23-6"><a href="comparações-de-parâmetros-de-duas-populações.html#cb23-6"></a><span class="kw">var.test</span>(vA,vB,<span class="dt">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
## 	F test to compare two variances
## 
## data:  vA and vB
## F = 1.4735, num df = 5, denom df = 7, p-value = 0.6176
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##   0.2788001 10.0981750
## sample estimates:
## ratio of variances 
##           1.473525</code></pre>
<p><strong>Interpretação no R</strong>: Observe que a função retorna a estatística do teste <span class="math inline">\(F = 1.4735\)</span> seguido pelos valores de graus de liberdade (<span class="math inline">\(df\)</span>, do inglês degrees of freedom) para o numerador (<span class="math inline">\(5\)</span>) e para o denominador (<span class="math inline">\(7\)</span>), e o valor-p (<span class="math inline">\(p-value = 0.6176\)</span>).</p>
<p><strong>Passo 1</strong>: Identificar o p-valor <span class="math inline">\(p-value\)</span> do teste:</p>
<p>O <span class="math inline">\(p-value\)</span> indica a probabilidade (área embaixo da curva) após o valor de <span class="math inline">\(F_{obs}\)</span>, ou seja, a probabilidade associada à estatística <span class="math inline">\(F_{obs}\)</span> foi de <span class="math inline">\(0,6176\)</span>, como apresentado abaixo:</p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><strong>PASSO 2:</strong> Comparar <span class="math inline">\(p-value\)</span> com o <span class="math inline">\(\alpha\)</span>.</p>
<p>Se <span class="math inline">\(p-value &gt; \alpha\)</span> então <strong>não rejeitamos</strong> <span class="math inline">\(H_0\)</span> e concluímos que as variâncias são iguais ou seja <strong>HOMOCEDÁSTICAS</strong>, caso contrário, <strong>rejeitamos</strong> <span class="math inline">\(H_0\)</span>.</p>
<p><strong>PASSO 3:</strong> Concluir o teste.</p>
<p>Para o nosso exemplo, <span class="math inline">\(p-value\)</span> foi maior que o <span class="math inline">\(\alpha\)</span>, ou seja:</p>
<p>Como <span class="math inline">\(p-value &gt; \alpha\)</span> <strong>não rejeitamos </strong> <span class="math inline">\(H_0\)</span> ao nível de 5% de significância, e concluímos que as variedades de milhos testadas são <strong>homocedásticas</strong>.</p>
</div>
<div id="comparação-de-duas-médias-de-populações-normais-amostras-independentes" class="section level2">
<h2><span class="header-section-number">2.2</span> Comparação de duas médias de populações normais: amostras independentes</h2>
<p>Com o objetivo de se comparar duas populações ou, sinonimamente, dois tratamentos, examinaremos a situação na qual os dados estão na forma de realizações de amostras aleatórias de tamanhos <span class="math inline">\(n_1\)</span> e <span class="math inline">\(n_2\)</span>, selecionadas, respectivamente, das populações 1 e 2.</p>
<p>Os dados são as medidas das respostas associadas com o seguinte delineamento experimental. Uma coleção de <span class="math inline">\(n_1 + n_2\)</span> elementos são aleatoriamente divididos em 2 grupos de tamanhos <span class="math inline">\(n_1\)</span> e <span class="math inline">\(n_2\)</span>, onde cada membro do primeiro grupo recebe o tratamento 1 e do segundo, o tratamento 2.</p>
<p>Especificamente, estaremos interessados em fazer inferência sobre o parâmetro: <span class="math inline">\(\mu_1 - \mu_2\)</span> (média da popilação 1) - (média da população 2)</p>
<p>Formalmente, suponha duas amostras aleatórias independentes de tamanhos <span class="math inline">\(n_1\)</span> e <span class="math inline">\(n_2\)</span> ou seja, <span class="math inline">\(X_1,X_2,...,X_{n_1}\)</span> e <span class="math inline">\(Y_1,Y_2,...,Y_{n_2}\)</span>, respectivamente, de uma população com distribuição <span class="math inline">\(N(\mu_1, \sigma_1^2)\)</span> e de uma população com distribuição <span class="math inline">\(N(\mu_2, \sigma_2^2)\)</span>.</p>
<p>Para cada uma dessas populações nós temos os seguitnes estiamdores <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\bar{y}\)</span> médias de população 1 e 2 respectivamente; <span class="math inline">\(s^2_1\)</span>, <span class="math inline">\(s^2_2\)</span> variâncias amostrais para as populações 1 e 2, respectivamente.</p>
<p><strong>Hipóteses:</strong>
<span class="math display">\[
\begin{cases} H_0:\mu_1=\mu_2, \; ou\;(\mu_1-\mu_2 = 0) \\ 
H_1: \mu_1\neq\mu_2, \; ou\;(\mu_1-\mu_2 \neq 0),\; bilateral
\end{cases}
\]</span></p>
<p>ou</p>
<p><span class="math display">\[
H_1: \mu_1 &gt;\mu_2, \; ou\;(\mu_1-\mu_2 &gt; 0),\; unilateral \; direita
\]</span></p>
<p>ou</p>
<p><span class="math display">\[
H_1: \mu_1 &lt; \mu_2, \; ou\;(\mu_1-\mu_2 &lt; 0),\; unilateral\; esquerda 
\]</span></p>
<p><strong>Estatística do Teste:</strong></p>
<p><span class="math display">\[
z = \frac{(\bar{x}-\bar{y})-(\mu_1-\mu_2)}{\sqrt{\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2}}}: N(0,1)
\]</span></p>
<p><strong>Caso 1: variâncias conhecidas</strong></p>
<p>Para testar a hipótese <span class="math inline">\(H_0\)</span> usa-se a estatística anterior.<br />
Ao supormos <span class="math inline">\(H_0\)</span> verdadeira então <span class="math inline">\(\mu_1-\mu_2 = 0\)</span>, portanto a estatística</p>
<p><span class="math display">\[
z = \frac{(\bar{x}-\bar{y})}{\sqrt{\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2}}}
\]</span></p>
<p>Tem distribuição <span class="math inline">\(N(0,1)\)</span>, portanto a região crítica do teste é construída a partir da <strong>Tabela Normal Padrão</strong></p>
<p><img src="tabNPad.png" /></p>
<p><a href="https://github.com/arpanosso/ExpAgr_2020/raw/master/TabelaNormal.pdf">Download da Tabela</a></p>
<p><strong>Caso 2: variâncias desconhecidas e iguais (Teste t)</strong></p>
<p>Preliminarmente, testa-se se as variâncias das duas populações são iguais, homocedásticas, pelo teste <strong>F de Snedecor</strong>.</p>
<p>Caso a hipótese <span class="math inline">\(H_0\)</span> não seja rejeitada, vamos utilizar a estatística estatística t com <span class="math inline">\(n_1+n_2 - 2\)</span> graus de liberdade:</p>
<p><span class="math display">\[
t = \frac{(\bar{x} - \bar{y})}{S_p \cdot \sqrt{\frac{1}{n_1} +\frac{1}{n_2}} }: t(n_1+n_2 - 2)
\]</span></p>
<p><span class="math inline">\(Sp\)</span> é o estimador não viciado do desvio padrão das populações, o qual é calculado por uma média ponderada:</p>
<p><span class="math display">\[
S_P=\sqrt{\frac{(n_1 - 1)\cdot s^2_1+(n_2-1)\cdot s^2_2}{(n_1 - 1)+(n_2-1)}}
\]</span>
Portanto a região crítica do teste é construída a partir da <strong>Tabela da distribuição t</strong> ao nível <span class="math inline">\(\alpha\)</span> com <span class="math inline">\(n_1+n_2 - 1\)</span> graus de liberdade.</p>
<p><img src="tabT.png" /></p>
<p><a href="https://github.com/arpanosso/ExpAgr_2020/raw/master/Tabela_tdeStudent.pdf">Download da Tabela</a></p>
<p><strong>Caso 3: variâncias desconhecidas e desiguais (Teste de Smith-Satterthwaite)</strong></p>
<p>Quando a hipótese de igualdade de variâncias for rejeitada, o a estatística do teste fica:</p>
<p><span class="math display">\[
t = \frac{(\bar{x}-\bar{y})}{\sqrt{\frac{s^2_1}{n_1}+\frac{s^2_2}{n_2}}}:
\]</span>
Essa estatística aproxima-se de uma dirtribuição t de Student com o número de graus de liberdade dado por, aproximadamente:</p>
<p><span class="math display">\[
gl&#39;=\frac{(\frac{s^2_1}{n_1}+\frac{s_2^2}{n_2})^2}{\frac{(\frac{s^2_1}{n_1})^2}{n_1-1}+\frac{(\frac{s^2_2}{n_2})^2}{n_2-1}}
\]</span>
Como o número de graus de liberdade assim calculado, geralmente, é <strong>não inteiro</strong>, recomenda-se aproximá-lo para o <strong>inteiro imediatamente anterior</strong> a este.</p>
<p><strong>EXEMPLO:</strong></p>
<p>Em um ensaio de competição de 2 cultivares de milho, onde a cultivar <span class="math inline">\(A\)</span> foi plantada e 6 parcelas (n=6 amostras) e a cultivar B em 8 parcelas amostras (n=8 amostras), as produções em kg/ha foram obervadas na tabela:</p>
<table>
<thead>
<tr class="header">
<th>Cultivar</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1470</td>
<td>1920</td>
<td>2340</td>
<td>2100</td>
<td>1920</td>
<td>1480</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>3260</td>
<td>3990</td>
<td>4050</td>
<td>3420</td>
<td>3510</td>
<td>3880</td>
<td>3550</td>
<td>3660</td>
<td></td>
</tr>
</tbody>
</table>
<p>Comparar ao nível de 5% de significância se as <strong>Médias</strong> desses cultivares são iguais.</p>
<p><strong>PASSO 1:</strong> Definir <span class="math inline">\(H_0\)</span> e <span class="math inline">\(H_1\)</span>.
<span class="math display">\[
H_0: \mu_1 = \mu_2 \text{   ou   } (\mu_1 - \mu_2 =0) \\
H_1: \mu_1 \neq \mu_2 \text{   ou   } (\mu_1 - \mu_2\neq 0)
\]</span></p>
<p><strong>PASSO 2:</strong> Calcular a estatística do teste para o <strong>caso 2 variâncias desconhecidas e iguais (Teste t)</strong>.</p>
<p>Calcular a média dos cultivares:</p>
<p>Cultivar A</p>
<p><span class="math display">\[
Média: \bar{x}  = 1871,667\;kg.ha^{-1}\\
Variância: s^2_1 = 118176.7\;[kg.ha^{-1}]^2
\]</span></p>
<p>Cultivar B</p>
<p><span class="math display">\[
Média: \bar{x}  = 3665\;kg.ha^{-1}\\
Variância: s^2_1 = 80200\;[kg.ha^{-1}]^2
\]</span>
Vamos estimar <span class="math inline">\(Sp\)</span>:</p>
<p><span class="math display">\[
S_P=\sqrt{\frac{(n_1 - 1)\cdot s^2_1+(n_2-1)\cdot s^2_2}{(n_1 - 1)+(n_2-1)}} =\sqrt{\frac{(6 - 1)\cdot 118176.7+(8-1)\cdot 80200}{(6 - 1)+(8-1)}} = 309,8768\;kg\;ha^{-1}
\]</span>
<img src="Rlogo.png" /></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="comparações-de-parâmetros-de-duas-populações.html#cb25-1"></a><span class="kw">sqrt</span>(((<span class="dv">6-1</span>)<span class="op">*</span><span class="fl">118176.7</span><span class="op">+</span>(<span class="dv">8-1</span>)<span class="op">*</span><span class="dv">80200</span>)<span class="op">/</span>(<span class="dv">6-1</span><span class="op">+</span><span class="dv">8-1</span>))</span></code></pre></div>
<pre><code>## [1] 309.8768</code></pre>
<p>Vamos calcular a estatística:</p>
<p><span class="math display">\[
t_{obs} = \frac{(\bar{x} - \bar{y})}{S_p \cdot \sqrt{\frac{1}{n_1} +\frac{1}{n_2}} }=\frac{(1871,667 - 3665)}{309,8768 \cdot \sqrt{\frac{1}{6} +\frac{1}{8}} } = -10,7159
\]</span></p>
<p><img src="R.png" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="comparações-de-parâmetros-de-duas-populações.html#cb27-1"></a>(<span class="fl">1871.667</span><span class="dv">-3665</span>)<span class="op">/</span>(<span class="fl">309.8768</span><span class="op">*</span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span><span class="op">+</span><span class="dv">1</span><span class="op">/</span><span class="dv">8</span>))</span></code></pre></div>
<pre><code>## [1] -10.7159</code></pre>
<p><strong>PASSO 3:</strong> Construir a Região Crítica.</p>
<p>Portanto a região crítica do teste é construída a partir da <strong>Tabela da distribuição t</strong> ao nível <span class="math inline">\(5\%\)</span> com $(6 + 8 - 2) = 12 $ graus de liberdade.</p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Olhando na tabela <span class="math inline">\(t_{(0,05; 12)} = 2,179\)</span></p>
<p>Assim, a <strong>região crítica</strong> do teste será <span class="math inline">\(RC = \{t &lt; -2,179 \;ou\;t&gt;2,179\}\)</span></p>
<p><strong>PASSO 4:</strong> Comparar <span class="math inline">\(t_{obs}\)</span> com o <span class="math inline">\(t_c\)</span>.</p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><strong>PASSO 5:</strong> Concluir o teste.</p>
<p>Como <span class="math inline">\(t_{obs} \in RC\)</span> <strong>rejeitamos </strong> <span class="math inline">\(H_0\)</span> ao nível de 5% de significância, e concluímos que as médias dos cultivares de milhos testadas são diferentes, ou seja, a cultivar B apresenta uma média maior que a cultivar A.</p>
<p><img src="Rlogo.png" /></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-1"></a><span class="co"># Construir os vetores de dados</span></span>
<span id="cb29-2"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-2"></a>vA&lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1470</span>,<span class="dv">1920</span>,<span class="dv">2340</span>,<span class="dv">2100</span>,<span class="dv">1920</span>,<span class="dv">1480</span>)</span>
<span id="cb29-3"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-3"></a>vB&lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3260</span>,<span class="dv">3990</span>,<span class="dv">4050</span>,<span class="dv">3420</span>,<span class="dv">3510</span>,<span class="dv">3880</span>,<span class="dv">3550</span>,<span class="dv">3660</span>)</span>
<span id="cb29-4"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-4"></a></span>
<span id="cb29-5"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-5"></a><span class="co"># Aplicar o teste de Médias, pelo teste t</span></span>
<span id="cb29-6"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-6"></a></span>
<span id="cb29-7"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-7"></a><span class="kw">t.test</span>(vA,vB,</span>
<span id="cb29-8"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-8"></a>       <span class="dt">alternative =</span> <span class="st">&quot;t&quot;</span>, <span class="co"># use t para bilateral, &quot;l&quot; para unilateral a esquerda e &quot;g&quot; para unilateral a direita</span></span>
<span id="cb29-9"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-9"></a>       <span class="dt">var.equal =</span> <span class="ot">TRUE</span>,  <span class="co"># TRUE se as variância forem iguais, caso contrário, FALSE</span></span>
<span id="cb29-10"><a href="comparações-de-parâmetros-de-duas-populações.html#cb29-10"></a>       <span class="dt">conf.level =</span> <span class="fl">0.95</span>) <span class="co"># Nível de confiança do teste</span></span></code></pre></div>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  vA and vB
## t = -10.716, df = 12, p-value = 1.688e-07
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2157.963 -1428.703
## sample estimates:
## mean of x mean of y 
##  1871.667  3665.000</code></pre>
<p><strong>Interpretação no R</strong>: Observe que a função retorna a estatística do teste <span class="math inline">\(t = -10.716\)</span> seguido pelos valores de graus de liberdade (<span class="math inline">\(df\)</span>) igual a <span class="math inline">\(12\)</span>, e o valor-p (<span class="math inline">\(p-value = 1.688e-07\)</span>) que significa <span class="math inline">\(0,0000001688\)</span>.</p>
<p>O <span class="math inline">\(p-value\)</span> indica a probabilidade (área embaixo da curva) antes do valor de <span class="math inline">\(t_{obs}\)</span>, no caso dele ser negativo, a probabilidade associada à estatística <span class="math inline">\(t_{obs}\)</span> foi de <span class="math inline">\(0,0000001688\)</span>, como apresentado abaixo. Se o valor de <span class="math inline">\(t_{obs}\)</span> for positivo, 0 <span class="math inline">\(p-value\)</span> indica a probabilidade (área embaixo da curva) depois do valor de <span class="math inline">\(t_{obs}\)</span></p>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p><strong>PASSO 2:</strong> Comparar <span class="math inline">\(p-value\)</span> com o <span class="math inline">\(\alpha\)</span>.</p>
<p>Se <span class="math inline">\(p-value &gt; \alpha\)</span> então <strong>não rejeitamos</strong> <span class="math inline">\(H_0\)</span> e concluímos que as médias são iguais, caso contrário, <strong>rejeitamos</strong> <span class="math inline">\(H_0\)</span>.</p>
<p><strong>PASSO 3:</strong> Concluir o teste.</p>
<p>Para o nosso exemplo, <span class="math inline">\(p-value\)</span> foi menor que o <span class="math inline">\(\alpha\)</span>, ou seja:</p>
<p>Como <span class="math inline">\(p-value &lt; \alpha\)</span> <strong>rejeitamos </strong> <span class="math inline">\(H_0\)</span> ao nível de 5% de significância, e concluímos que os cultivares de milhos testadas são apresentam médias diferentes.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="planejamento-de-experimentos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["curso_GIEU.pdf", "curso_GIEU.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
