<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 8 DELINEAMENTO EM BLOCOS CASUALIZADOS | Curso do R do GIEU</title>
  <meta name="description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 8 DELINEAMENTO EM BLOCOS CASUALIZADOS | Curso do R do GIEU" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 8 DELINEAMENTO EM BLOCOS CASUALIZADOS | Curso do R do GIEU" />
  
  <meta name="twitter:description" content="Etapa do curso visando a apresentação da análise dos principais delineamentos experimentais utilizando o R" />
  

<meta name="author" content="José C. Barbosa &amp; Alan R. Panosso" />


<meta name="date" content="2020-10-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="desdobramento-de-graus-de-liberdade-de-tratamentos.html"/>
<link rel="next" href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">curso_GIEU</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> INTRODUÇÃO AO CURSO</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#alguns-conceitos-básicos"><i class="fa fa-check"></i><b>1.1</b> Alguns conceitos básicos</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#medidas-de-posição-e-de-tendência-central"><i class="fa fa-check"></i><b>1.2</b> Medidas de posição e de tendência central</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html"><i class="fa fa-check"></i><b>2</b> COMPARAÇÕES DE PARÂMETROS DE DUAS POPULAÇÕES</a><ul>
<li class="chapter" data-level="2.1" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html#comparação-da-variância-de-duas-populações-normais"><i class="fa fa-check"></i><b>2.1</b> Comparação da variância de duas populações normais</a></li>
<li class="chapter" data-level="2.2" data-path="comparações-de-parâmetros-de-duas-populações.html"><a href="comparações-de-parâmetros-de-duas-populações.html#comparação-de-duas-médias-de-populações-normais-amostras-independentes"><i class="fa fa-check"></i><b>2.2</b> Comparação de duas médias de populações normais: amostras independentes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html"><i class="fa fa-check"></i><b>3</b> PLANEJAMENTO DE EXPERIMENTOS</a><ul>
<li class="chapter" data-level="3.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>3.1</b> Introdução</a></li>
<li class="chapter" data-level="3.2" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#unidade-experimental-ou-parcela"><i class="fa fa-check"></i><b>3.2</b> Unidade Experimental ou Parcela</a></li>
<li class="chapter" data-level="3.3" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#princípios-básicos-da-experimentação"><i class="fa fa-check"></i><b>3.3</b> Princípios Básicos da Experimentação</a></li>
<li class="chapter" data-level="3.4" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#relação-entre-os-princípios-básico-da-experimentação-e-os-delineamentos-experimentais"><i class="fa fa-check"></i><b>3.4</b> Relação entre os princípios básico da experimentação e os delineamentos experimentais</a></li>
<li class="chapter" data-level="3.5" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#testes-de-significância"><i class="fa fa-check"></i><b>3.5</b> Testes de Significância</a></li>
<li class="chapter" data-level="3.6" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#teste-f-de-snedecor-para-análise-de-variância"><i class="fa fa-check"></i><b>3.6</b> Teste F de Snedecor para Análise de Variância</a></li>
<li class="chapter" data-level="3.7" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#exemplo-de-aplicação-do-teste-f"><i class="fa fa-check"></i><b>3.7</b> Exemplo de aplicação do teste F</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html"><i class="fa fa-check"></i><b>4</b> TESTES PARA COMPARAÇÃO DE MÉDIAS</a><ul>
<li class="chapter" data-level="4.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>4.1</b> Introdução</a></li>
<li class="chapter" data-level="4.2" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#contrastes-de-médias"><i class="fa fa-check"></i><b>4.2</b> Contrastes de Médias</a></li>
<li class="chapter" data-level="4.3" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#estimativa-do-contrastes"><i class="fa fa-check"></i><b>4.3</b> Estimativa do Contrastes</a></li>
<li class="chapter" data-level="4.4" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#covariância-entre-dois-contrastes"><i class="fa fa-check"></i><b>4.4</b> Covariância entre dois contrastes</a></li>
<li class="chapter" data-level="4.5" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>4.5</b> Contrastes ortogonais</a></li>
<li class="chapter" data-level="4.6" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#variância-de-um-contraste"><i class="fa fa-check"></i><b>4.6</b> Variância de um contraste</a></li>
<li class="chapter" data-level="4.7" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#erro-padrão-do-contraste"><i class="fa fa-check"></i><b>4.7</b> Erro padrão do contraste</a></li>
<li class="chapter" data-level="4.8" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-t-de-student"><i class="fa fa-check"></i><b>4.8</b> Teste t de Student</a></li>
<li class="chapter" data-level="4.9" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-t-de-student"><i class="fa fa-check"></i><b>4.9</b> Exemplo de aplicação do teste t de Student</a></li>
<li class="chapter" data-level="4.10" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-tukey"><i class="fa fa-check"></i><b>4.10</b> Teste de Tukey</a></li>
<li class="chapter" data-level="4.11" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-tukey"><i class="fa fa-check"></i><b>4.11</b> Exemplo de aplicação do teste de Tukey</a></li>
<li class="chapter" data-level="4.12" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-duncan"><i class="fa fa-check"></i><b>4.12</b> Teste de Duncan</a></li>
<li class="chapter" data-level="4.13" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-duncan"><i class="fa fa-check"></i><b>4.13</b> Exemplo de aplicação do teste de Duncan</a></li>
<li class="chapter" data-level="4.14" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#teste-de-scheffé"><i class="fa fa-check"></i><b>4.14</b> Teste de Scheffé</a></li>
<li class="chapter" data-level="4.15" data-path="testes-para-comparação-de-médias.html"><a href="testes-para-comparação-de-médias.html#exemplo-de-aplicação-do-teste-de-scheffé"><i class="fa fa-check"></i><b>4.15</b> Exemplo de aplicação do teste de Scheffé</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html"><i class="fa fa-check"></i><b>5</b> DELINEAMENTO INTEIRAMENTE CASUALIZADO</a><ul>
<li class="chapter" data-level="5.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#caracterização"><i class="fa fa-check"></i><b>5.1</b> Caracterização</a></li>
<li class="chapter" data-level="5.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático"><i class="fa fa-check"></i><b>5.2</b> Modelo Matemático</a></li>
<li class="chapter" data-level="5.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#hipóteses-básicas-para-aplicação-da-análoise-de-variância"><i class="fa fa-check"></i><b>5.3</b> Hipóteses básicas para aplicação da análoise de variância</a></li>
<li class="chapter" data-level="5.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>5.4</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="5.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>5.5</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><i class="fa fa-check"></i><b>6</b> DELINEAMENTO INTEIRAMENTE CASUALIZADO COM NÚMERO DIFERENTE DE REPETIÇÕES POR TRATAMENTO</a><ul>
<li class="chapter" data-level="6.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>6.1</b> Introdução</a></li>
<li class="chapter" data-level="6.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>6.2</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="6.3" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-das-médias-e-error-padrôes-das-médias"><i class="fa fa-check"></i><b>6.3</b> Cálculo das médias e error padrôes das médias</a></li>
<li class="chapter" data-level="6.4" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#teste-de-tukey-para-comparação-das-médias"><i class="fa fa-check"></i><b>6.4</b> Teste de Tukey para comparação das médias</a></li>
<li class="chapter" data-level="6.5" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>6.5</b> Cálculo do coeficiente de variação do experimento</a></li>
<li class="chapter" data-level="6.6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#aplicação-do-teste-t-de-student-a-um-contraste"><i class="fa fa-check"></i><b>6.6</b> Aplicação do teste t de Student a um contraste</a></li>
<li class="chapter" data-level="6.7" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#teste-de-duncan-para-a-comparação-das-médias"><i class="fa fa-check"></i><b>6.7</b> Teste de Duncan para a comparação das médias</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><i class="fa fa-check"></i><b>7</b> DESDOBRAMENTO DE GRAUS DE LIBERDADE DE TRATAMENTOS</a><ul>
<li class="chapter" data-level="7.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>7.1</b> Introdução</a></li>
<li class="chapter" data-level="7.2" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#obtenção-da-análise-de-variância-com-desdobramento-dos-graus-de-liberdade-de-tratamentos"><i class="fa fa-check"></i><b>7.2</b> Obtenção da análise de variância com desdobramento dos graus de liberdade de tratamentos</a></li>
<li class="chapter" data-level="7.3" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#método-dos-contrastes-de-totais-de-tratamentos"><i class="fa fa-check"></i><b>7.3</b> Método dos contrastes de totais de tratamentos</a></li>
<li class="chapter" data-level="7.4" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#método-dos-totais-de-tratamentos-sem-utilizar-contrastes"><i class="fa fa-check"></i><b>7.4</b> Método dos totais de tratamentos (sem utilizar contrastes)</a></li>
<li class="chapter" data-level="7.5" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#análise-de-variância-com-desdobramento-dos-graus-de-liberdade-de-tratamentos"><i class="fa fa-check"></i><b>7.5</b> Análise de variância com desdobramento dos graus de liberdade de tratamentos</a><ul>
<li class="chapter" data-level="7.5.1" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#conclusões"><i class="fa fa-check"></i><b>7.5.1</b> <strong>Conclusões</strong></a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="desdobramento-de-graus-de-liberdade-de-tratamentos.html"><a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html#componentes-com-maisde-um-grau-de-liberdade"><i class="fa fa-check"></i><b>7.6</b> Componentes com maisde um grau de liberdade</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="delineamento-em-blocos-casualizados.html"><a href="delineamento-em-blocos-casualizados.html"><i class="fa fa-check"></i><b>8</b> DELINEAMENTO EM BLOCOS CASUALIZADOS</a><ul>
<li class="chapter" data-level="8.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#caracterização"><i class="fa fa-check"></i><b>8.1</b> Caracterização</a></li>
<li class="chapter" data-level="8.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#modelo-matemático"><i class="fa fa-check"></i><b>8.2</b> Modelo matemático</a></li>
<li class="chapter" data-level="8.3" data-path="delineamento-em-blocos-casualizados.html"><a href="delineamento-em-blocos-casualizados.html#hipóteses-básicas"><i class="fa fa-check"></i><b>8.3</b> Hipóteses básicas</a></li>
<li class="chapter" data-level="8.4" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>8.4</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="8.5" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>8.5</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><i class="fa fa-check"></i><b>9</b> DELINEAMENTO EM BLOCOS CASUALIZADOS COM UMA PARCELA PERDIDA</a><ul>
<li class="chapter" data-level="9.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>9.1</b> Introdução</a></li>
<li class="chapter" data-level="9.2" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#estimativa-da-parcela-perdida"><i class="fa fa-check"></i><b>9.2</b> Estimativa da parcela perdida</a></li>
<li class="chapter" data-level="9.3" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>9.3</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="9.4" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#médias-de-tratamentos"><i class="fa fa-check"></i><b>9.4</b> Médias de tratamentos</a></li>
<li class="chapter" data-level="9.5" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#erros-padrões-das-médias"><i class="fa fa-check"></i><b>9.5</b> Erros padrões das médias</a></li>
<li class="chapter" data-level="9.6" data-path="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html"><a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html#comparação-de-médias-pelo-teste-de-tukey"><i class="fa fa-check"></i><b>9.6</b> Comparação de médias pelo teste de Tukey</a></li>
<li class="chapter" data-level="9.7" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#exemplo-de-aplicação"><i class="fa fa-check"></i><b>9.7</b> Exemplo de aplicação</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html"><i class="fa fa-check"></i><b>10</b> EXPERIMENTOS FATORIAIS</a><ul>
<li class="chapter" data-level="10.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>10.1</b> Introdução</a></li>
<li class="chapter" data-level="10.2" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-simples-de-um-fator"><i class="fa fa-check"></i><b>10.2</b> Efeito simples de um fator</a></li>
<li class="chapter" data-level="10.3" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-principal-de-um-fator"><i class="fa fa-check"></i><b>10.3</b> Efeito principal de um fator</a></li>
<li class="chapter" data-level="10.4" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#efeito-da-interação-entre-fatores"><i class="fa fa-check"></i><b>10.4</b> Efeito da interação entre fatores</a></li>
<li class="chapter" data-level="10.5" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#vantagens-dos-experimentos-fatoriais"><i class="fa fa-check"></i><b>10.5</b> Vantagens dos experimentos fatoriais</a></li>
<li class="chapter" data-level="10.6" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#desvantagens-dos-experimentos-fatoriais"><i class="fa fa-check"></i><b>10.6</b> Desvantagens dos experimentos fatoriais</a></li>
<li class="chapter" data-level="10.7" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#classificação-dos-experementos-fatoriais"><i class="fa fa-check"></i><b>10.7</b> Classificação dos Experementos Fatoriais</a></li>
<li class="chapter" data-level="10.8" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#casualização-dos-tratamentos"><i class="fa fa-check"></i><b>10.8</b> Casualização dos tratamentos</a></li>
<li class="chapter" data-level="10.9" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#análise-de-variância-de-um-experimento-fatorial-com-2-fatores-com-interação-não-significativa"><i class="fa fa-check"></i><b>10.9</b> Análise de variância de um experimento fatorial com 2 fatores com interação não significativa</a></li>
<li class="chapter" data-level="10.10" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>10.10</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="10.11" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#cálculo-das-média-de-tratamento-do-solo-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>10.11</b> Cálculo das média de Tratamento do Solo e erros padrões das médias</a></li>
<li class="chapter" data-level="10.12" data-path="experimentos-fatoriais.html"><a href="experimentos-fatoriais.html#cálculo-das-média-de-fungicidas-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>10.12</b> Cálculo das média de Fungicidas e erros padrões das médias</a></li>
<li class="chapter" data-level="10.13" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>10.13</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><i class="fa fa-check"></i><b>11</b> ANÁLISE DE UM EXPERIMENTO FATORIAL COM 2 FATORES, COM INTERAÇÃO SIGNIFICATIVA</a><ul>
<li class="chapter" data-level="11.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>11.1</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="11.2" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#desdobrando-a-interação-itimes-d-para-estudar-os-efeitos-do-fator-doses-em-cada-nível-do-fator-inseticida-d-d.-i"><i class="fa fa-check"></i><b>11.2</b> Desdobrando a interação <span class="math inline">\(I\times D\)</span>, para estudar os efeitos do fator <strong>DOSES</strong> em cada nível do fator <strong>INSETICIDA</strong> (D d. I):</a></li>
<li class="chapter" data-level="11.3" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#desdobrando-a-interação-i-times-d-para-estudar-os-efeitos-do-fator-inseticidas-dentro-de-cada-nível-do-fator-dose-d-d.-i"><i class="fa fa-check"></i><b>11.3</b> Desdobrando a interação <span class="math inline">\(I \times D\)</span>, para estudar os efeitos do fator <strong>INSETICIDAS</strong> dentro de cada nível do fator <strong>DOSE</strong> (D d. I):</a></li>
<li class="chapter" data-level="11.4" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#teste-de-tukey-para-a-comparação-de-médias"><i class="fa fa-check"></i><b>11.4</b> Teste de Tukey para a comparação de médias</a></li>
<li class="chapter" data-level="11.5" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#para-comparar-médias-de-inseticidas-na-dose-1-i-d.-d_1"><i class="fa fa-check"></i><b>11.5</b> Para comparar médias de Inseticidas na Dose 1 (I d. <span class="math inline">\(D_1\)</span>)</a></li>
<li class="chapter" data-level="11.6" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#para-comparar-médias-de-inseticidas-na-dose-2-i-d.-d_2"><i class="fa fa-check"></i><b>11.6</b> Para comparar médias de Inseticidas na Dose 2 (I d. <span class="math inline">\(D_2\)</span>)</a></li>
<li class="chapter" data-level="11.7" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>11.7</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html"><i class="fa fa-check"></i><b>12</b> Estudo do Fatorial <span class="math inline">\(3^2\)</span></a><ul>
<li class="chapter" data-level="12.1" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>12.1</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="12.2" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#desdobrando-a-interação-etimes-d-para-estudar-os-efeitos-do-fator-espaçamento-em-cada-nível-do-fator-densidade-e-d.-d"><i class="fa fa-check"></i><b>12.2</b> Desdobrando a interação <span class="math inline">\(E\times D\)</span>, para estudar os efeitos do fator <strong>Espaçamento</strong> em cada nível do fator <strong>Densidade</strong> (E d. D):</a></li>
<li class="chapter" data-level="12.3" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#desdobrando-a-interação-etimes-d-para-estudar-os-efeitos-do-fator-densidade-em-cada-nível-do-fator-espaçamentos-d-d.-e"><i class="fa fa-check"></i><b>12.3</b> Desdobrando a interação <span class="math inline">\(E\times D\)</span>, para estudar os efeitos do fator <strong>Densidade</strong> em cada nível do fator <strong>Espaçamentos</strong> (D d. E):</a></li>
<li class="chapter" data-level="12.4" data-path="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html"><a href="análise-de-um-experimento-fatorial-com-2-fatores-com-interação-significativa.html#teste-de-tukey-para-a-comparação-de-médias"><i class="fa fa-check"></i><b>12.4</b> Teste de Tukey para a comparação de médias</a></li>
<li class="chapter" data-level="12.5" data-path="estudo-do-fatorial-32.html"><a href="estudo-do-fatorial-32.html#resultado-do-teste-de-tukey"><i class="fa fa-check"></i><b>12.5</b> Resultado do teste de Tukey</a></li>
<li class="chapter" data-level="12.6" data-path="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html"><a href="delineamento-inteiramente-casualizado-com-número-diferente-de-repetições-por-tratamento.html#cálculo-do-coeficiente-de-variação-do-experimento"><i class="fa fa-check"></i><b>12.6</b> Cálculo do coeficiente de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html"><i class="fa fa-check"></i><b>13</b> Estudo do Fatorial <span class="math inline">\(2^3\)</span></a><ul>
<li class="chapter" data-level="13.1" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#análise-de-variância-de-um-experimento-fatorial-23"><i class="fa fa-check"></i><b>13.1</b> Análise de variância de um experimento fatorial <span class="math inline">\(2^3\)</span></a></li>
<li class="chapter" data-level="13.2" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-das-somas-de-quadrados-pelo-método-dos-contrastes-de-totais-de-tratamentos."><i class="fa fa-check"></i><b>13.2</b> Cálculo das somas de quadrados pelo método dos contrastes de totais de tratamentos.</a></li>
<li class="chapter" data-level="13.3" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#desdobramento-da-interação-n-times-k"><i class="fa fa-check"></i><b>13.3</b> Desdobramento da Interação <span class="math inline">\(N \times K\)</span></a></li>
<li class="chapter" data-level="13.4" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-das-médias-e-erros-padrões-das-médias"><i class="fa fa-check"></i><b>13.4</b> Cálculo das médias e erros padrões das médias</a></li>
<li class="chapter" data-level="13.5" data-path="estudo-do-fatorial-23.html"><a href="estudo-do-fatorial-23.html#cálculo-do-coeficiente-de-variação"><i class="fa fa-check"></i><b>13.5</b> Cálculo do coeficiente de variação</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html"><i class="fa fa-check"></i><b>14</b> Experimentos em Parcelas Subdivididas</a><ul>
<li class="chapter" data-level="14.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>14.1</b> Introdução</a></li>
<li class="chapter" data-level="14.2" data-path="delineamento-inteiramente-casualizado.html"><a href="delineamento-inteiramente-casualizado.html#obtenção-da-análise-de-variância"><i class="fa fa-check"></i><b>14.2</b> Obtenção da análise de variância</a></li>
<li class="chapter" data-level="14.3" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#desdobramento-da-interação-e-times-v-para-estudar-os-efeitos-de-variedades-dentro-de-cada-época-de-plantio-v-d.-e"><i class="fa fa-check"></i><b>14.3</b> 1. Desdobramento da interação E <span class="math inline">\(\times\)</span> V para estudar os efeitos de Variedades dentro de cada Época de plantio (V d. E):</a></li>
<li class="chapter" data-level="14.4" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#desdobramento-da-interação-e-times-v-para-estudar-os-efeitos-de-épocas-dentro-de-cada-variedade-e-d.-v"><i class="fa fa-check"></i><b>14.4</b> 2. Desdobramento da interação E <span class="math inline">\(\times\)</span> V para estudar os efeitos de Épocas dentro de cada Variedade (E d. V):</a></li>
<li class="chapter" data-level="14.5" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-das-médias"><i class="fa fa-check"></i><b>14.5</b> Cálculo das médias</a></li>
<li class="chapter" data-level="14.6" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-dos-erros-padrões"><i class="fa fa-check"></i><b>14.6</b> Cálculo dos erros padrões:</a></li>
<li class="chapter" data-level="14.7" data-path="experimentos-em-parcelas-subdivididas.html"><a href="experimentos-em-parcelas-subdivididas.html#cálculo-dos-coeficientes-de-variação-do-experimento"><i class="fa fa-check"></i><b>14.7</b> Cálculo dos coeficientes de variação do experimento</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html"><i class="fa fa-check"></i><b>15</b> Análise de Regressão por Polinômios Ortogonais</a><ul>
<li class="chapter" data-level="15.1" data-path="planejamento-de-experimentos.html"><a href="planejamento-de-experimentos.html#introdução"><i class="fa fa-check"></i><b>15.1</b> Introdução</a></li>
<li class="chapter" data-level="15.2" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#obtenção-da-análise-de-variância-estudando-se-os-efeitos-da-regressão"><i class="fa fa-check"></i><b>15.2</b> Obtenção da análise de variância, estudando-se os efeitos da regressão</a></li>
<li class="chapter" data-level="15.3" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#coeficientes-de-interpolação-de-polinômios-ortogonais"><i class="fa fa-check"></i><b>15.3</b> Coeficientes de interpolação de polinômios ortogonais</a></li>
<li class="chapter" data-level="15.4" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#obtendo-a-equação-de-regressão"><i class="fa fa-check"></i><b>15.4</b> Obtendo a Equação de Regressão</a></li>
<li class="chapter" data-level="15.5" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#cálculo-do-coeficiente-de-determinação-r²"><i class="fa fa-check"></i><b>15.5</b> Cálculo do Coeficiente de Determinação (R²)</a></li>
<li class="chapter" data-level="15.6" data-path="análise-de-regressão-por-polinômios-ortogonais.html"><a href="análise-de-regressão-por-polinômios-ortogonais.html#gráfico-da-regressão-ajustada"><i class="fa fa-check"></i><b>15.6</b> Gráfico da Regressão Ajustada</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso do R do GIEU</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="delineamento-em-blocos-casualizados" class="section level1">
<h1><span class="header-section-number">Capítulo 8</span> DELINEAMENTO EM BLOCOS CASUALIZADOS</h1>
<div id="caracterização" class="section level2">
<h2><span class="header-section-number">8.1</span> Caracterização</h2>
<p>O delineamento em blocos casualizados (DBC) é o mais utilizado dos delineamentos experimentais, e os experimentos instalados de acordo com esse delineamento são denominados de <strong>experimentos em blocos casualizados</strong> ou <strong>experimentos em blocos ao acaso</strong>. Além dos princípios da <strong><em>repetição</em></strong> e da <strong><em>casualização</em></strong>, leva em conta também o princípio do <strong><em>controle local</em></strong>.</p>
<p>Sempre que houver dúvidas a respeito da homogeneidade das condições experimentais é conveniente usar o princípio do controle local, estabelecendo blocos com parcelas homogêneas.</p>
<p><strong>As principais características deste delineamento são</strong>:</p>
<ol style="list-style-type: decimal">
<li><p>As parcelas são distribuídas em grupos ou blocos (princípio do controle local) de tal forma que elas sejam o mais uniforme possível dentro de cada bloco.</p></li>
<li><p>O número de parcelas por bloco deve ser igual ao número de tratamentos (blocos completos casualizados).</p></li>
<li><p>Os tratamentos são designados às parcelas de forma casual, sendo essa casualização feita dentro de cada bloco.</p></li>
</ol>
<p>Esse delineamento é mais eficiente que o delineamento inteiramente casualizado, e essa eficiência depende da uniformidade das parcelas dentro de cada bloco, podendo inclusive, haver diferenças acentuadas de um bloco para outro.</p>
<p>Então, por exemplo, se temos um experimento em blocos casualizados em que desejamos estudar o efeito de 4 variedades (V1,V2,V3 e V4), sendo cada uma delas repetidas 5 vezes, teremos o seguinte plano experimental:</p>
<p><img src="DBC_d.png" /></p>
<p>Note que dentro de cada bloco temos as variedades sorteadas ao acaso. Caso este mesmo ensaio fosse montado no delineamento inteiramente casualizados, o sorteio seria feito em todas as parcelas do experimento, e os tratamentos não seriam agrupados em blocos. Por exemplo, no delineamento inteiramente casualizado teríamos:</p>
<p><img src="DIC_d.png" /></p>
<p>E eficiência do delineamento em blocos casualizados depende de uniformidade das parcelas dentro de cada bloco. De um bloco para outro, pode haver variação.</p>
<p>A forma e a distribuição dos blocos no campo depende apenas da uniformidade das condições experimentais.</p>
<p>Os blocos podem ser retangulares, quadrados ou irregulares:</p>
<p><img src="blocos.jpg" /></p>
<p>Os blocos podem ser espalhados em toda a área de estudo, ou então agrupados um ao lado do outro. Geralmente se coloca um bloco ao lado do outro para facilitar a condução do experimento.</p>
<p>Os blocos são utilizados para controlar pequenas diferenças que ocorrem entre as parcelas experimentais, tais como, diferenças de fertilidade do solo, diferenças de disponibilidade de água, diferenças de luminosidade (no caso de casas de vegetação), etc.</p>
<p><strong>As principais vantagens desse delineamento são:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Controla as diferenças que ocorrem nas condições experimentais de um bloco para outro.</p></li>
<li><p>Permite, dentro de certos limites, utilizar qualquer número de tratamentos e blocos.</p></li>
<li><p>Nos conduz a uma estimativa mais exata para a variância residual.</p></li>
<li><p>A análise de variância é relativamente simples, sendo apenas um pouco mais demorada que a do delineamento inteiramente casualizado, pois possui uma causa de variação a mais (Blocos).</p></li>
</ol>
<p><strong>As principais desvantagens desse delineamento são:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Pela utilização do princípio do controle local há uma diminuição no número de graus de liberdade do resíduo.</p></li>
<li><p>A exigência de homogeneidade dentro do bloco limita o número de tratamentos, que não pode ser muito grande.</p></li>
</ol>
</div>
<div id="modelo-matemático" class="section level2">
<h2><span class="header-section-number">8.2</span> Modelo matemático</h2>
<p>Para podermos analisar um experimento em qualquer delineamento, necessitamos conhecer o modelo matemático do mesmo, e aceitar algumas hipóteses básicas necessárias para a validade da análise de variância.</p>
<p>O modelo matemático do delineamento em blocos casualizados é o seguinte:</p>
<p><span class="math display">\[
x_{ij} = \mu +\tau_i + \beta_j+\epsilon_{ij}
\]</span></p>
<p>onde,
<span class="math inline">\(x_{ij}\)</span> representa o valor esperado na parcela que recebeu o tratamento <span class="math inline">\(i\)</span> e que se encontra no bloco <span class="math inline">\(j\)</span>.</p>
<p><span class="math inline">\(\mu\)</span> é a média geral do experimento.</p>
<p><span class="math inline">\(\tau_i\)</span> é o efeito devido ao tratamento <em>i</em> que foi aplicado à parcela.</p>
<p><span class="math inline">\(\beta_j\)</span> é o efeito devido ao bloco <em>j</em> em que se encontra a parcela.</p>
<p><span class="math inline">\(\epsilon_{ij}\)</span> é o efeito dos fatores não controlados ou acaso na parcela que recebeu o tratamento <em>i</em> e que se encontra no bloco <em>j</em>.</p>
</div>
<div id="hipóteses-básicas" class="section level2">
<h2><span class="header-section-number">8.3</span> Hipóteses básicas</h2>
<p>As hipóteses básicas para a validade da análise de variância são as mesmas já vistas para o delineamento inteiramente casualizado, ou seja:</p>
<p><strong>Aditividade</strong>: Os efeitos dos fatores do modelo são aditivos</p>
<p><strong>Independência</strong>: Os erros (desvios) <span class="math inline">\(\epsilon_{ij}\)</span>, devido aos efeitos de fatores não controlados ou acaso devem ser independentes</p>
<p><strong>Homocedasticidade (homogeneidade de variâncias)</strong>: Os erros (desvios) <span class="math inline">\(\epsilon_{ij}\)</span>, devido ao acaso devem possuir variância comum <span class="math inline">\(\sigma^2\)</span></p>
<p><strong>Normalidade dos desvios</strong>: Os erros ou desvios <span class="math inline">\(\epsilon_{ij}\)</span> devido ao acaso devem possuir distribuição normal de probabilidades.</p>
<p>Uma forma resumida de apresentar estas quatro pressuposições é apresentada a seguir:</p>
<p><span class="math display">\[
\epsilon_{ij} \overset{iid}{\tilde{}} N(0,\sigma^2) \\
\]</span></p>
<p>Os erros ou desvios <span class="math inline">\(\epsilon_{ij}\)</span> são independentes e identicamente distribuídos, de acordo com uma distribuição normal, com média zero e variância comum <span class="math inline">\(\sigma^2\)</span>.</p>
</div>
<div id="obtenção-da-análise-de-variância" class="section level2">
<h2><span class="header-section-number">8.4</span> Obtenção da análise de variância</h2>
<p>Para a obtenção da análise de variância, vamos considerar um experimento genérico em blocos casualizados com <span class="math inline">\(I\)</span> tratamentos e <span class="math inline">\(J\)</span> blocos. Os dados obtidos podem ser dispostos num quadro como o seguinte:</p>
<table>
<colgroup>
<col width="42%" />
<col width="3%" />
<col width="3%" />
<col width="11%" />
<col width="3%" />
<col width="11%" />
<col width="3%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th>Tratamentos</th>
<th>1</th>
<th>2</th>
<th>…</th>
<th><span class="math inline">\(j\)</span></th>
<th>…</th>
<th><span class="math inline">\(J\)</span></th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(x_{11}\)</span></td>
<td><span class="math inline">\(x_{12}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{1j}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{1J}\)</span></td>
<td><span class="math inline">\(T_1=\sum_{j=1}^Jx_{1j}\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(x_{21}\)</span></td>
<td><span class="math inline">\(x_{22}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{2j}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{2J}\)</span></td>
<td><span class="math inline">\(T_2=\sum_{j=1}^Jx_{2j}\)</span></td>
</tr>
<tr class="odd">
<td>…</td>
<td></td>
<td></td>
<td>…</td>
<td></td>
<td>…</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(i\)</span></td>
<td><span class="math inline">\(x_{i1}\)</span></td>
<td><span class="math inline">\(x_{i2}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{ij}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{iJ}\)</span></td>
<td><span class="math inline">\(T_i=\sum_{j=1}^Jx_{ij}\)</span></td>
</tr>
<tr class="odd">
<td>…</td>
<td></td>
<td></td>
<td>…</td>
<td></td>
<td>…</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(I\)</span></td>
<td><span class="math inline">\(x_{I1}\)</span></td>
<td><span class="math inline">\(x_{I2}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{Ij}\)</span></td>
<td>…</td>
<td><span class="math inline">\(x_{IJ}\)</span></td>
<td><span class="math inline">\(T_I=\sum_{j=1}^Jx_{Ij}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><span class="math inline">\(B_1=\sum_{i=1}^Ix_{i1}\)</span></td>
<td><span class="math inline">\(B_2=\sum_{i=1}^Ix_{i2}\)</span></td>
<td>…</td>
<td><span class="math inline">\(B_j=\sum_{i=1}^Ix_{ij}\)</span></td>
<td>…</td>
<td><span class="math inline">\(B_J=\sum_{i=1}^Ix_{iJ}\)</span></td>
<td><span class="math inline">\(G=\sum_{i=1}^I\sum_{j=1}^Jx_{ij}\)</span></td>
</tr>
</tbody>
</table>
<p>Pelo método dos mínimos quadrados, devemos obter as estimativas de <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\tau_i\)</span> e <span class="math inline">\(\beta_j\)</span> que minimizam a soma de quadrados dos erros do modelo:</p>
<p><span class="math display">\[
x_{ij} = \mu +\tau_i + \beta_j+\epsilon_{ij}
\]</span></p>
<p>Então, temos:</p>
<p><span class="math display">\[
\hat{m} = \frac{\sum_{i=1}^I\sum_{j=1}^Jx_{ij}}{IJ}=\frac{G}{IJ} \\
\hat{t_i}=\frac{T_i}{J}-\hat{m}=\hat{m_i}-\hat{m} \\
\hat{b_j}=\frac{B_j}{I}-\hat{m}=\hat{m_j}-\hat{m}
\]</span></p>
<p>Podemos agora obter as somas de quadrados para cada um desses efeitos. As somas de quadrados total e devido ao efeito de tratamentos são obtidas da mesma maneira que no delineamento inteiramente casualizado:</p>
<p><span class="math display">\[
SQ_{Total}=\sum_{i=1}^{I}\sum_{j=1}^Jx_{ij}-C\\
SQ_{Trat}=\frac{1}{J}\sum_{i=1}^IT_i^2-C \\
onde,\; C=\frac{G^2}{IJ}
\]</span></p>
<p>A soma de quadrados devido ao efeito de blocos é obtida por:
<span class="math display">\[
SQ_{Blocos} = I\hat{b_1^2}+I\hat{b_2^2}+...+I\hat{b_J^2} \\
SQ_{Blocos} = I(\hat{b_1^2}+\hat{b_2^2}+...+\hat{b_J^2})\\
SQ_{Blocos} = I\left[ \left(\frac{B_1}{I}-\hat{m} \right)^2+\left(   \frac{B_2}{I}-\hat{m} \right)^2+...+\left( \frac{B_J}{I}-\hat{m} \right)^2 \right]\\
SQ_{Blocos} = I\left[ \left(\frac{B_1^2}{I^2}-2\hat{m}\frac{B_1}{I}+\hat{m}^2 \right)+\left(\frac{B_2^2}{I^2}-2\hat{m}\frac{B_2}{I}+\hat{m}^2
\right)+...+\left(  \frac{B_J^2}{I^2}-2\hat{m}\frac{B_J}{I}+\hat{m^2}\right) \right] \\
SQ_{Blocos} =\left[\left(\frac{B_1^2}{I}+\frac{B_2^2}{I}+...+\frac{B_J^2}{I}\right)-2\hat{m}(B_1+B_2+...+B_J)+ IJ\hat{m}^2 \right] \\
SQ_{Blocos} = \frac{1}{I}(B_1^2+B_2^2+...+B_J^2)-2\hat{m}G+IJ\frac{G^2}{(IJ)^2}\\
SQ_{Blocos} =\frac{1}{I}\sum_{j=1}^JB_j^2-C
\]</span></p>
<p>A soma de quadrados devido ao efeito dos fatores não controlados ou acaso (<span class="math inline">\(SQ_{Resíduo}\)</span>), é obtida por diferença:</p>
<p><span class="math display">\[
SQ_{Resíduo} = SQ_{Total} - SQ_{Trat} - SQ_{Blocos}
\]</span></p>
<table>
<thead>
<tr class="header">
<th>Causas de Variação</th>
<th>GL</th>
<th>SQ</th>
<th>QM</th>
<th>F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tratamentos</td>
<td><span class="math inline">\(I-1\)</span></td>
<td><span class="math inline">\(SQ_{Trat}\)</span></td>
<td><span class="math inline">\(SQ_{Trat}\)</span>/(I-1)</td>
<td><span class="math inline">\(QM_{Trat}\)</span>/<span class="math inline">\(QM_{Res}\)</span></td>
</tr>
<tr class="even">
<td>Blocos</td>
<td><span class="math inline">\(J-1\)</span></td>
<td><span class="math inline">\(SQ_{Blocos}\)</span></td>
<td><span class="math inline">\(SQ_{Blocos}\)</span>/(J-1)</td>
<td><span class="math inline">\(QM_{Blocos}\)</span>/<span class="math inline">\(QM_{Res}\)</span></td>
</tr>
<tr class="odd">
<td>Resíduo</td>
<td><span class="math inline">\((I-1)(J-1)\)</span></td>
<td><span class="math inline">\(SQ_{Res}\)</span></td>
<td><span class="math inline">\(SQ_{Res}\)</span>/[(I-1)(J-1)]</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><span class="math inline">\(IJ-1\)</span></td>
<td><span class="math inline">\(SQ_{Total}\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>HIPÓTESES TESTADAS:</strong></p>
<p><strong>Para Tratamentos</strong>:
<span class="math display">\[
\begin{cases} H_0: t_i=0, i=1,2, ...,I. \\
H_1:pelo\;menos\;um \;valor\;t_i \neq 0
\end{cases}
\]</span></p>
<p><strong>Para Blocos</strong>:</p>
<p><span class="math display">\[
\begin{cases} H_0: b_j=0, j=1,2, ...,J. \\
H_1:pelo\;menos\;um \;valor\;b_j \neq 0
\end{cases}
\]</span></p>
<p><strong>CRITÉRIO DO TESTE</strong>:</p>
<p><strong>Para Tratamentos</strong>:</p>
<p>Comparamos o valor F calculado para tratamentos com o valor de F tabelado em função do número de GL de Tratamentos e GL do resíduo, ao nível <span class="math inline">\(\alpha\)</span> de significância.</p>
<p>Se <span class="math inline">\(F_{Trat} &gt; F_{Tab}\)</span>, concluímos que o teste é significativo, portanto, rejeitamos <span class="math inline">\(H_0\)</span> e devemos concluir que existe diferença significativa entre os efeitos dos tratamentos testados em relação à variáveis (característica) em estudo.</p>
<p><strong>Para Blocos</strong>:</p>
<p>Pra Blocos, a comparação é feita entre o valor de F calculado com o F tabelado em função do número de GL de Blocos e GL do resíduo, ao nível <span class="math inline">\(\alpha\)</span> de significância</p>
<p>Se <span class="math inline">\(F_{Blocos} &gt; F_{Tab}\)</span>, concluímos que o teste é significativo, portanto, rejeitamos <span class="math inline">\(H_0\)</span> e devemos concluir que os blocos possuem efeitos diferentes em relação à característica em estudo, ou seja, os blocos foram eficientes no controle da heterogeneidade local.</p>
</div>
<div id="exemplo-de-aplicação" class="section level2">
<h2><span class="header-section-number">8.5</span> Exemplo de aplicação</h2>
<p>No trabalho “Influência do genótipo e da adubação sobre algumas características fenotípicas de <em>Zea mays</em> L (Milho)”, realizado por BARBOSA (1976), foram utilizadas 4 cultivares de milho:</p>
<p><span class="math inline">\(C_1\)</span> = OPACO 2</p>
<p><span class="math inline">\(C_2\)</span> = PIRANÃO</p>
<p><span class="math inline">\(C_3\)</span> = COMPOSTO FLINT</p>
<p><span class="math inline">\(C_4\)</span> = AGROCERES AG-152</p>
<p>O ensaio foi montado de acordo com o delineamento em blocos casualizados, sendo utilizados 5 blocos para controlar as diferenças de fertilidade do solo entre terraços.</p>
<p>Os resultados obtidos para a produção em kg/ha, foram os seguintes e podem ser encontrados online em <a href="https://github.com/arpanosso/ExpAgr_2020/blob/master/dados/milho.txt">milho</a>.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Tratamentos
</th>
<th style="text-align:right;">
Bloco1
</th>
<th style="text-align:right;">
Bloco2
</th>
<th style="text-align:right;">
Bloco3
</th>
<th style="text-align:right;">
Bloco4
</th>
<th style="text-align:right;">
Bloco5
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
OPACO2
</td>
<td style="text-align:right;">
2812
</td>
<td style="text-align:right;">
2296
</td>
<td style="text-align:right;">
3501
</td>
<td style="text-align:right;">
3301
</td>
<td style="text-align:right;">
3691
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
15601
</td>
</tr>
<tr>
<td style="text-align:left;">
PIRANAO
</td>
<td style="text-align:right;">
3728
</td>
<td style="text-align:right;">
3588
</td>
<td style="text-align:right;">
4418
</td>
<td style="text-align:right;">
4544
</td>
<td style="text-align:right;">
5084
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
21362
</td>
</tr>
<tr>
<td style="text-align:left;">
COMP.FLINT
</td>
<td style="text-align:right;">
5359
</td>
<td style="text-align:right;">
5106
</td>
<td style="text-align:right;">
7477
</td>
<td style="text-align:right;">
8007
</td>
<td style="text-align:right;">
7956
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
33905
</td>
</tr>
<tr>
<td style="text-align:left;">
AG152
</td>
<td style="text-align:right;">
4482
</td>
<td style="text-align:right;">
4510
</td>
<td style="text-align:right;">
5236
</td>
<td style="text-align:right;">
5930
</td>
<td style="text-align:right;">
5025
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
25183
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: black !important;background-color: lightgray !important;">
Total
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
16381
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
15500
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
20632
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
21782
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;">
21756
</td>
<td style="text-align:right;font-weight: bold;color: black !important;background-color: lightgray !important;font-weight: bold;color: black !important;background-color: lightgray !important;">
96051
</td>
</tr>
</tbody>
</table>
<p>As hipóteses que desejamos testar são as seguintes:</p>
<p><span class="math display">\[
\begin{cases} H_0: As\;cultivares\;testadas\;não\;diferem\;entre\;si\;em\;relação\;à\;produção\;da\;cultura\;do\;milho. \\
H_1: As\;cultivares\;testadas\;diferem\;entre\;si\;em\;relação\;à\;produção\;da\;cultura\;do\;milho.
\end{cases}
\]</span></p>
<p>Para obtenção da análise de variância, devemos, inicialmente, obter as Somas de Quadrados:</p>
<p><strong>a) Soma de quadrados total</strong>:</p>
<p><span class="math display">\[
SQ_{Total} = \sum_{i=1}^I\sum_{j=i}^Jx_{ij}^2 - C \\
SQ_{Total} = \sum_{i=1}^I\sum_{j=i}^Jx_{ij}^2 - \frac{G^2}{IJ} \\
SQ_{Total} = (2812^2+2296^2+...+3501^2) - \frac{96051^2}{4\cdot5}\\
SQ_{Total} = 47817032,90
\]</span></p>
<p><strong>b) Soma de quadrados devido ao efeito de tratamentos</strong>:</p>
<p><span class="math display">\[
SQ_{Trat} = \frac{\sum_{i=1}^IT_i^2}{J} - C \\
SQ_{Trat} = \frac{T_1^2+T_2^2+...+T_I^2}{J} - \frac{G^2}{IJ}\\
SQ_{Trat} = \frac{15601^2+21362^2+33905^2+25183^2}{5} - \frac{96051^2}{4\cdot5}\\ SQ_{Trat}= 35402021,70
\]</span></p>
<p><strong>c) Soma de quadrados devido ao efeito de blocos</strong>:</p>
<p><span class="math display">\[
SQ_{Blocos} = \frac{\sum_{j=1}^JB_j^2}{I} - C \\
SQ_{Blocos} = \frac{B_1^2+B_2^2+...+B_J^2}{I} - \frac{G^2}{IJ}\\
SQ_{Blocos} = \frac{16381^2+15500^2+20632^2+21782^2+21756^2}{4} - \frac{96051^2}{4\cdot5}\\ SQ_{Blocos}= 9221681,20
\]</span></p>
<p><strong>d) Soma de quadrados do resíduo</strong>:</p>
<p><span class="math display">\[
SQ_{Res} = SQ_{Total} - SQ_{Trat} - SQ_{Blocos}\\
SQ_{Res} = 47817032,9-35402021,7-9221681,2=3193330,00
\]</span></p>
<p>Então podemos montar o seguinte quadro de análise de variância:</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Causas.de.Variação
</th>
<th style="text-align:left;">
GL
</th>
<th style="text-align:left;">
SQ
</th>
<th style="text-align:left;">
QM
</th>
<th style="text-align:left;">
F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Tratamento
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
35402021,7
</td>
<td style="text-align:left;">
11800673,9
</td>
<td style="text-align:left;">
44,34**
</td>
</tr>
<tr>
<td style="text-align:left;">
Blocos
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
9221681,2
</td>
<td style="text-align:left;">
2305420,3
</td>
<td style="text-align:left;">
8,66**
</td>
</tr>
<tr>
<td style="text-align:left;">
Resíduo
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
3193330,00
</td>
<td style="text-align:left;">
266110,83
</td>
<td style="text-align:left;">
–
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
47817032,9
</td>
<td style="text-align:left;">
–
</td>
<td style="text-align:left;">
–
</td>
</tr>
</tbody>
</table>
<p>Valores de F da tabela para tratamentos (3 x 12 GL):<span class="math inline">\(\begin{cases} 5\%=3,49 \\ 1\%=5,95 \end{cases}\)</span></p>
<p>Valores de F da tabela para blocos (4 x 12 GL):<span class="math inline">\(\begin{cases} 5\%=3,26 \\ 1\%=5,41 \end{cases}\)</span></p>
<p><strong>Conclusões</strong>:</p>
<p><strong>a) Para Tratamentos</strong>: O teste F foi significativo ao nível de <span class="math inline">\(1\%\)</span> de probabilidade, indicando que devemos rejeitar <span class="math inline">\(H_0\)</span> e concluir que as cultivares diferem entre si em relação à produção da cultura do milho, com um grau de confiança superior a <span class="math inline">\(99\%\)</span> de probabilidade.</p>
<p><strong>b) Para Blocos</strong>: O teste F foi significativo ao nível de <span class="math inline">\(1\%\)</span> de probabilidade, indicando que devemos rejeitar <span class="math inline">\(H_0\)</span> e concluir que as diferenças de fertilidade do solo entre terraços apresentaram efeitos diferentes sobre a produção do milho, com um grau de confiança superior a <span class="math inline">\(99\%\)</span> de probabilidade.</p>
<p>Para tirar conclusões mais específicas sobre o comportamento das cultivares, devemos utilizar um teste de comparação de médias.</p>
<p><strong>a) Cálculo das médias de cada tratamento e erros padrões das médias</strong>:</p>
<p>Então, no nosso exemplo, temos:
<span class="math display">\[
\hat{m_1} = \frac{T_1}{J}=\frac{15601}{5}=3120,20\;kg/ha\\
\hat{m_2} = \frac{T_2}{J}=\frac{21362}{5}=4272,40\;kg/ha\\
\hat{m_3} = \frac{T_3}{J}=\frac{33905}{5}=6781,00\;kg/ha\\
\hat{m_4} = \frac{T_4}{J}=\frac{25183}{5}=5036,60\;kg/ha\\
\]</span></p>
<p>Erro padrão dessas médias será:</p>
<p><span class="math display">\[
s(\hat{m}) = \frac{s}{\sqrt{J}}=\sqrt{\frac{QM_{Res}}{J}} =\sqrt{\frac{266110,83}{5}}=230,70\;kg/ha
\]</span></p>
<p><strong>b) Aplicação do teste de Tukey </strong>:</p>
<p><strong>b.1. Cálculo do valor de <span class="math inline">\(\Delta\)</span></strong>:</p>
<p><span class="math display">\[
q_{(4\;trat\times12\;GLres)}(5\%) = 4,20\\
s=\sqrt{QM_{Res}}=515,8593,\;com\; r=5 \\
DMS=q\cdot\sqrt{\frac{QM_{Res}}{r}}=4,20\cdot\sqrt{\frac{266110,83}{5}}=968,94\;kg/ha
\]</span></p>
<p><strong>b.2. Cálculo das estimativas dos contrastes entre duas médias</strong>:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(\hat{m_3}\)</span></th>
<th><span class="math inline">\(\hat{m_4}\)</span></th>
<th><span class="math inline">\(\hat{m_2}\)</span></th>
<th><span class="math inline">\(\hat{m_1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat{m_3}\)</span></td>
<td>-</td>
<td>1744,4*</td>
<td>2508,60*</td>
<td>3660,80*</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat{m_4}\)</span></td>
<td>-</td>
<td>-</td>
<td>764,20</td>
<td>1916,40*</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat{m_2}\)</span></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>1152,20*</td>
</tr>
</tbody>
</table>
<p><strong>b.3. Conclusão</strong>: Médias seguidas de pela mesma letra não diferem entre si pelo teste de Tukey, ao nível de 5% de probabilidade.</p>
<p><span class="math display">\[
\hat{m_3} = 6781,00\;kg/ha\;\;\;\;-a\\
\hat{m_4} = 5036,60\;kg/ha\;\;\;\;-b\\
\hat{m_2} = 4272,40\;kg/ha\;\;\;\;-b\\
\hat{m_1} = 3120,20\;kg/ha\;\;\;\;-c\\
\]</span></p>
<p>Portanto, a melhor cultivar foi o Composto Flint, pois diferiu das demais pelo teste de Tukey e apresentou maior produtividade.</p>
<p><strong>c) Cálculo do coeficiente de variação do experimento</strong>:
<span class="math display">\[
\hat{m}=\frac{G}{IJ}=\frac{96051}{4\cdot5}=4802,55\;kg/ha\\
s=\sqrt{QM_{Res}}=\sqrt{226110,83}=515,8593\;kg/ha\\
CV=\frac{100\cdot s}{\hat{m}}=\frac{100\cdot515,8593}{4802,55}=10,74\%
\]</span></p>
<p><strong>Aplicação no R</strong></p>
<p><img src="R.png" /></p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="delineamento-em-blocos-casualizados.html#cb102-1"></a>caminho&lt;-<span class="st">&quot;https://raw.githubusercontent.com/arpanosso/ExpAgr_2020/master/dados/milho.txt&quot;</span></span>
<span id="cb102-2"><a href="delineamento-em-blocos-casualizados.html#cb102-2"></a>dados&lt;-<span class="kw">read.table</span>(caminho,<span class="dt">h=</span>T,<span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</span>
<span id="cb102-3"><a href="delineamento-em-blocos-casualizados.html#cb102-3"></a><span class="kw">head</span>(dados)</span></code></pre></div>
<pre><code>##      trat bloco    y
## 1  OPACO2     1 2812
## 2  OPACO2     2 2296
## 3  OPACO2     3 3501
## 4  OPACO2     4 3301
## 5  OPACO2     5 3691
## 6 PIRANAO     1 3728</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="delineamento-em-blocos-casualizados.html#cb104-1"></a><span class="co"># Extraindo os fatores e a variável resposta</span></span>
<span id="cb104-2"><a href="delineamento-em-blocos-casualizados.html#cb104-2"></a>trat&lt;-<span class="kw">as.factor</span>(dados<span class="op">$</span>trat)</span>
<span id="cb104-3"><a href="delineamento-em-blocos-casualizados.html#cb104-3"></a>bloco&lt;-<span class="kw">as.factor</span>(dados<span class="op">$</span>bloco)</span>
<span id="cb104-4"><a href="delineamento-em-blocos-casualizados.html#cb104-4"></a>y&lt;-dados<span class="op">$</span>y</span>
<span id="cb104-5"><a href="delineamento-em-blocos-casualizados.html#cb104-5"></a></span>
<span id="cb104-6"><a href="delineamento-em-blocos-casualizados.html#cb104-6"></a><span class="co"># Definindo o modelo matemático</span></span>
<span id="cb104-7"><a href="delineamento-em-blocos-casualizados.html#cb104-7"></a>modelo&lt;-<span class="kw">aov</span>(y<span class="op">~</span>trat<span class="op">+</span>bloco)</span>
<span id="cb104-8"><a href="delineamento-em-blocos-casualizados.html#cb104-8"></a><span class="kw">anova</span>(modelo)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: y
##           Df   Sum Sq  Mean Sq F value    Pr(&gt;F)    
## trat       3 35402022 11800674 44.3450 9.068e-07 ***
## bloco      4  9221681  2305420  8.6634   0.00158 ** 
## Residuals 12  3193330   266111                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="delineamento-em-blocos-casualizados.html#cb106-1"></a><span class="co">#Comparação de Médias pelo teste de Tukey</span></span>
<span id="cb106-2"><a href="delineamento-em-blocos-casualizados.html#cb106-2"></a><span class="kw">require</span>(<span class="st">&quot;agricolae&quot;</span>)</span>
<span id="cb106-3"><a href="delineamento-em-blocos-casualizados.html#cb106-3"></a>glRes&lt;-<span class="kw">df.residual</span>(modelo)</span>
<span id="cb106-4"><a href="delineamento-em-blocos-casualizados.html#cb106-4"></a>QMres&lt;-<span class="kw">deviance</span>(modelo)<span class="op">/</span>glRes</span>
<span id="cb106-5"><a href="delineamento-em-blocos-casualizados.html#cb106-5"></a>tukey &lt;-<span class="st"> </span><span class="kw">HSD.test</span>(modelo,<span class="st">&quot;trat&quot;</span>, <span class="dt">group=</span><span class="ot">TRUE</span>,<span class="dt">console=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Study: modelo ~ &quot;trat&quot;
## 
## HSD Test for y 
## 
## Mean Square Error:  266110.8 
## 
## trat,  means
## 
##                 y       std r  Min  Max
## AG152      5036.6  596.4368 5 4482 5930
## COMP.FLINT 6781.0 1431.4177 5 5106 8007
## OPACO2     3120.2  565.1997 5 2296 3691
## PIRANAO    4272.4  616.1240 5 3588 5084
## 
## Alpha: 0.05 ; DF Error: 12 
## Critical Value of Studentized Range: 4.19866 
## 
## Minimun Significant Difference: 968.628 
## 
## Treatments with the same letter are not significantly different.
## 
##                 y groups
## COMP.FLINT 6781.0      a
## AG152      5036.6      b
## PIRANAO    4272.4      b
## OPACO2     3120.2      c</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="delineamento-em-blocos-casualizados.html#cb108-1"></a><span class="kw">bar.group</span>(tukey<span class="op">$</span>groups,</span>
<span id="cb108-2"><a href="delineamento-em-blocos-casualizados.html#cb108-2"></a>          <span class="dt">las=</span><span class="dv">1</span>,</span>
<span id="cb108-3"><a href="delineamento-em-blocos-casualizados.html#cb108-3"></a>          <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(y)<span class="op">*</span><span class="fl">1.10</span>),</span>
<span id="cb108-4"><a href="delineamento-em-blocos-casualizados.html#cb108-4"></a>          <span class="dt">xlab=</span><span class="st">&quot;Cultivares&quot;</span>,</span>
<span id="cb108-5"><a href="delineamento-em-blocos-casualizados.html#cb108-5"></a>          <span class="dt">ylab=</span><span class="st">&quot;Produção (kg por ha)&quot;</span>,</span>
<span id="cb108-6"><a href="delineamento-em-blocos-casualizados.html#cb108-6"></a>          <span class="dt">main=</span><span class="st">&quot;Teste de Tukey (5%)&quot;</span>);<span class="kw">box</span>()</span></code></pre></div>
<p><img src="curso_GIEU_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="delineamento-em-blocos-casualizados.html#cb109-1"></a><span class="co"># Cálculo do CV</span></span>
<span id="cb109-2"><a href="delineamento-em-blocos-casualizados.html#cb109-2"></a>cv&lt;-<span class="dv">100</span><span class="op">*</span><span class="kw">sqrt</span>(QMres)<span class="op">/</span><span class="kw">mean</span>(y)</span>
<span id="cb109-3"><a href="delineamento-em-blocos-casualizados.html#cb109-3"></a><span class="kw">paste</span>(<span class="kw">round</span>(cv,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;10.74%&quot;</code></pre>
<p>Utilizando o pacote “ExpDes.pt”</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="delineamento-em-blocos-casualizados.html#cb111-1"></a><span class="co"># Carregando o pacote para a análise</span></span>
<span id="cb111-2"><a href="delineamento-em-blocos-casualizados.html#cb111-2"></a><span class="kw">library</span>(ExpDes.pt)</span>
<span id="cb111-3"><a href="delineamento-em-blocos-casualizados.html#cb111-3"></a></span>
<span id="cb111-4"><a href="delineamento-em-blocos-casualizados.html#cb111-4"></a><span class="co"># verificando os 6 primeiros registros</span></span>
<span id="cb111-5"><a href="delineamento-em-blocos-casualizados.html#cb111-5"></a><span class="kw">head</span>(dados)</span></code></pre></div>
<pre><code>##      trat bloco    y
## 1  OPACO2     1 2812
## 2  OPACO2     2 2296
## 3  OPACO2     3 3501
## 4  OPACO2     4 3301
## 5  OPACO2     5 3691
## 6 PIRANAO     1 3728</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="delineamento-em-blocos-casualizados.html#cb113-1"></a><span class="co"># Análise de variância e teste de Tukey com a função dbc</span></span>
<span id="cb113-2"><a href="delineamento-em-blocos-casualizados.html#cb113-2"></a>trat &lt;-<span class="st"> </span>dados<span class="op">$</span>trat <span class="co"># Criando o vetor de tratamentos</span></span>
<span id="cb113-3"><a href="delineamento-em-blocos-casualizados.html#cb113-3"></a>bloco &lt;-<span class="st"> </span>dados<span class="op">$</span>bloco <span class="co"># Criando o vetor dos blocos</span></span>
<span id="cb113-4"><a href="delineamento-em-blocos-casualizados.html#cb113-4"></a>y &lt;-<span class="st"> </span>dados<span class="op">$</span>y <span class="co"># Criando o vetor com a variável resposta</span></span>
<span id="cb113-5"><a href="delineamento-em-blocos-casualizados.html#cb113-5"></a></span>
<span id="cb113-6"><a href="delineamento-em-blocos-casualizados.html#cb113-6"></a><span class="co"># Utilizando a função</span></span>
<span id="cb113-7"><a href="delineamento-em-blocos-casualizados.html#cb113-7"></a><span class="kw">dbc</span>(trat,bloco,y,<span class="dt">mcomp =</span> <span class="st">&quot;tukey&quot;</span>)</span></code></pre></div>
<pre><code>## ------------------------------------------------------------------------
## Quadro da analise de variancia
## ------------------------------------------------------------------------
##            GL       SQ QM     Fc      Pr&gt;Fc
## Tratamento  3 35402022  2 44.345 0.00000091
## Bloco       4  9221681  3  8.663 0.00158020
## Residuo    12  3193330  4                  
## Total      19 47817033  1                  
## ------------------------------------------------------------------------
## CV = 10.74 %
## 
## ------------------------------------------------------------------------
## Teste de normalidade dos residuos 
## valor-p:  0.1786606 
## De acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.
## ------------------------------------------------------------------------
## 
## ------------------------------------------------------------------------
## Teste de homogeneidade de variancia 
## valor-p:  0.03461775 
## ATENCAO: a 5% de significancia, as variancias nao podem ser consideradas homogeneas!
## ------------------------------------------------------------------------
## 
## Teste de Tukey
## ------------------------------------------------------------------------
## Grupos Tratamentos Medias
## a 	 COMP.FLINT 	 6781 
##  b 	 AG152 	 5036.6 
##  b 	 PIRANAO 	 4272.4 
##   c 	 OPACO2 	 3120.2 
## ------------------------------------------------------------------------</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="desdobramento-de-graus-de-liberdade-de-tratamentos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="delineamento-em-blocos-casualizados-com-uma-parcela-perdida.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["curso_GIEU.pdf", "curso_GIEU.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
